export interface EcosystemApp {
  id: string;
  name: string;
  codeName: string;
  pillar: "cyber-defense" | "enterprise-portals" | "sphera-ecosystem" | "connectin-os" | "campus-ecosystem" | "talent-commerce" | "social-impact";
  categoryLabel: string;
  description: string;
  badge: "Platform" | "Portal" | "SuperApp" | "AI Engine" | "Vercel Live" | "Enterprise" | "Impact";
  status: "ONLINE" | "STANDALONE" | "PROD_ACTIVE" | "INTEGRATED";
  vercelUrl: string; // Guaranteed global Vercel production URL
  mirrorVercelUrl?: string;
  customDomain?: string;
  localPort?: number;
  localPath?: string;
  internalRoute?: string;
  githubRepo?: string;
  githubUrl?: string;
  techStack: string[];
  features: string[];
  icon: string;
  accentColor: string;
  stats?: {
    label: string;
    value: string;
  };
}

export interface EcosystemPillar {
  id: string;
  title: string;
  shortName: string;
  tagline: string;
  icon: string;
  gradient: string;
  borderGlow: string;
  count: number;
}

export const ECOSYSTEM_PILLARS: EcosystemPillar[] = [
  {
    id: "all",
    title: "All Ecosystem Applications",
    shortName: "All Apps",
    tagline: "Unified index of all 34 platforms, microservices, and portals with global Vercel URLs",
    icon: "LayoutGrid",
    gradient: "from-blue-600 to-cyan-500",
    borderGlow: "rgba(59, 130, 246, 0.4)",
    count: 34,
  },
  {
    id: "cyber-defense",
    title: "Autonomous Cyber Defense & AST Suite",
    shortName: "Cyber Defense (05–19)",
    tagline: "Static & dynamic analysis, threat modeling, malware sandbox & attack path engines",
    icon: "ShieldAlert",
    gradient: "from-cyan-500 to-blue-600",
    borderGlow: "rgba(6, 182, 212, 0.4)",
    count: 16,
  },
  {
    id: "enterprise-portals",
    title: "Core Enterprise Portals & Gateways",
    shortName: "Enterprise Portals",
    tagline: "Consulting advisory, client portals, VeritasLens AI, governance & SOC dispatch",
    icon: "Building2",
    gradient: "from-indigo-600 to-violet-600",
    borderGlow: "rgba(99, 102, 241, 0.4)",
    count: 5,
  },
  {
    id: "sphera-ecosystem",
    title: "Sphera Social & Collaborative Studio",
    shortName: "Sphera Studio",
    tagline: "15 simulation worlds, verified practitioner social graph, studio & FastAPI backend",
    icon: "Layers",
    gradient: "from-purple-500 to-pink-500",
    borderGlow: "rgba(168, 85, 247, 0.4)",
    count: 6,
  },
  {
    id: "connectin-os",
    title: "ConnectIn Professional Super App",
    shortName: "ConnectIn OS",
    tagline: "30 roadmap pillars, verified reputation graph, B2B procurement, defense labs & 2FA IAM",
    icon: "Workflow",
    gradient: "from-emerald-500 to-teal-600",
    borderGlow: "rgba(168, 85, 247, 0.4)",
    count: 4,
  },
  {
    id: "campus-ecosystem",
    title: "Campus & Student Operating Platform",
    shortName: "CampusSync",
    tagline: "18-module campus ecosystem, TigerOrbit 360 live radar, OneCard wallet & TUHousing",
    icon: "GraduationCap",
    gradient: "from-amber-500 to-orange-500",
    borderGlow: "rgba(245, 158, 11, 0.4)",
    count: 3,
  },
  {
    id: "talent-commerce",
    title: "Talent, Commerce & Standalone Apps",
    shortName: "Talent & Commerce",
    tagline: "CareerOrbit AI talent matcher, BAZAAR marketplace & Axiom encrypted mail suite",
    icon: "Sparkles",
    gradient: "from-rose-500 to-pink-600",
    borderGlow: "rgba(244, 63, 94, 0.4)",
    count: 3,
  },
  {
    id: "social-impact",
    title: "Global Social Impact & Initiatives",
    shortName: "Social Impact",
    tagline: "CSRTA E-Waste sustainability survey, SkillHands vocational exchange & housing",
    icon: "Globe",
    gradient: "from-green-500 to-emerald-600",
    borderGlow: "rgba(34, 197, 94, 0.4)",
    count: 4,
  },
];

export const ECOSYSTEM_APPS: EcosystemApp[] = [
  // ==========================================
  // PILLAR 1: AUTONOMOUS CYBER DEFENSE & AST SUITE (05-19 + STRIKE)
  // ==========================================
  {
    id: "platform-05-sast",
    name: "SAST Platform (v1)",
    codeName: "Platform 05",
    pillar: "cyber-defense",
    categoryLabel: "Static Application Security Testing",
    description: "Multi-engine static code analysis powered by CodeQL, Semgrep, Joern syntax tree models, and AI false positive suppression.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://05-sast-platform.vercel.app",
    localPort: 3005,
    localPath: "platforms/05-sast-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/05-sast-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "CodeQL Engine", "Semgrep"],
    features: ["CodeQL Deep Ast Scan", "Semgrep Ruleset", "Joern CPG Engine", "AI Confidence Score"],
    icon: "FileCode2",
    accentColor: "#06b6d4",
    stats: { label: "Scan Velocity", value: "3,200 ev/s" },
  },
  {
    id: "platform-06-sca",
    name: "SCA Platform",
    codeName: "Platform 06",
    pillar: "cyber-defense",
    categoryLabel: "Software Composition & SBOM",
    description: "Deep open-source dependency analysis, CycloneDX/SPDX SBOM generation, license compliance audit, and automated CVE correlation.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://06-sca-platform.vercel.app",
    localPort: 3006,
    localPath: "platforms/06-sca-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/06-sca-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "CycloneDX", "NVD Sync"],
    features: ["SBOM Generator", "License Compliance", "Dependency Graph", "CVE Correlator"],
    icon: "PackageCheck",
    accentColor: "#3b82f6",
    stats: { label: "Telemetry Throughput", value: "2,840 ev/s" },
  },
  {
    id: "platform-07-secrets",
    name: "Secrets Detection Platform",
    codeName: "Platform 07",
    pillar: "cyber-defense",
    categoryLabel: "Credential & Key Leak Prevention",
    description: "Entropy-based secret scanning, Git commit history hunter, Shannon entropy analysis, and active token validation verification.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://07-secrets-platform.vercel.app",
    localPort: 3007,
    localPath: "platforms/07-secrets-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/07-secrets-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "Git History Engine", "Shannon Entropy"],
    features: ["Git History Scan", "Entropy Analysis", "Token Live Verifier", "Pre-Commit Hooks"],
    icon: "KeyRound",
    accentColor: "#6366f1",
    stats: { label: "Entropy Precision", value: "99.5%" },
  },
  {
    id: "platform-08-container",
    name: "Container Security Platform",
    codeName: "Platform 08",
    pillar: "cyber-defense",
    categoryLabel: "Container Image & Runtime Security",
    description: "OCI container image layer vulnerability auditing, rootless daemon inspection, Trivy engine integration, and base image recommendations.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://08-container-security-platform.vercel.app",
    localPort: 3008,
    localPath: "platforms/08-container-security-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/08-container-security-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "OCI Runtime", "Trivy"],
    features: ["Image Layer Audit", "Rootless Daemon Check", "Dockerfile Linter", "CVE Patch Matcher"],
    icon: "Boxes",
    accentColor: "#0ea5e9",
    stats: { label: "Layer Depth", value: "100% OCI" },
  },
  {
    id: "platform-09-k8s",
    name: "Kubernetes Security Platform",
    codeName: "Platform 09",
    pillar: "cyber-defense",
    categoryLabel: "K8s RBAC & Cluster Hardening",
    description: "Cluster configuration auditing, overly permissive RBAC privilege path detection, admission controller validation, and Pod Security Standards enforcement.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://09-k8s-security-platform.vercel.app",
    localPort: 3009,
    localPath: "platforms/09-k8s-security-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/09-k8s-security-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "K8s Client", "RBAC Graph"],
    features: ["RBAC Path Analyzer", "Admission Controller", "Pod Security Standards", "K8s Misconfig Engine"],
    icon: "Network",
    accentColor: "#38bdf8",
    stats: { label: "Cluster Audit", value: "Real-Time" },
  },
  {
    id: "platform-10-iac",
    name: "IaC Security Platform",
    codeName: "Platform 10",
    pillar: "cyber-defense",
    categoryLabel: "Infrastructure as Code Security",
    description: "Static security linting and compliance analysis for Terraform, AWS CloudFormation, Ansible, ARM templates, and Pulumi definitions.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://10-iac-security-platform.vercel.app",
    localPort: 3010,
    localPath: "platforms/10-iac-security-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/10-iac-security-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "Terraform HCL", "Checkov Parser"],
    features: ["Terraform HCL Audit", "CloudFormation Linter", "Policy-as-Code", "Drift Detection"],
    icon: "FileSliders",
    accentColor: "#14b8a6",
    stats: { label: "Rule Coverage", value: "1,400+ Checks" },
  },
  {
    id: "platform-11-dast",
    name: "DAST / AXIOM Security Intelligence (v2)",
    codeName: "Platform 11",
    pillar: "cyber-defense",
    categoryLabel: "Dual SAST-2 / DAST Dynamic Testing",
    description: "Dynamic web and API testing gateway with Engine Brain v4 orchestrator, Vuln Probe Registry, multi-target AST fuzzer, and real-time AI copilot.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://11-dast-security-platform.vercel.app",
    localPort: 3011,
    localPath: "platforms/11-dast-security-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/11-dast-security-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "Engine Brain v4", "OWASP ZAP"],
    features: ["Engine Brain v4", "Vuln Probe Registry", "Multi-Target AST Fuzzer", "Active AI Copilot"],
    icon: "ShieldAlert",
    accentColor: "#f43f5e",
    stats: { label: "Telemetry Stream", value: "5,820 ev/s" },
  },
  {
    id: "platform-12-api",
    name: "API Security Platform",
    codeName: "Platform 12",
    pillar: "cyber-defense",
    categoryLabel: "REST, GraphQL & gRPC API Security",
    description: "Automated API schema fuzzing, BOLA/IDOR detection, rate-limit boundary testing, token injection verification, and OWASP API Top 10 coverage.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://12-api-security-platform.vercel.app",
    localPort: 3012,
    localPath: "platforms/12-api-security-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/12-api-security-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "OpenAPI Fuzzer", "GraphQL AST"],
    features: ["BOLA/IDOR Hunter", "OpenAPI 3.1 Importer", "GraphQL Fuzzing", "OWASP API Top 10"],
    icon: "Webhook",
    accentColor: "#a855f7",
    stats: { label: "Endpoint Coverage", value: "100% REST/GQL" },
  },
  {
    id: "platform-13-mobile",
    name: "Mobile AppSec Platform",
    codeName: "Platform 13",
    pillar: "cyber-defense",
    categoryLabel: "iOS & Android Mobile Binary Security",
    description: "iOS IPA and Android APK bytecode decompilation, hardcoded credential discovery, ATS/manifest configuration audits, and dynamic Frida runtime instrumentation.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://13-mobile-security-platform.vercel.app",
    localPort: 3013,
    localPath: "platforms/13-mobile-security-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/13-mobile-security-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "Frida Runtime", "JADX Engine"],
    features: ["Frida Instrumentation", "APK Decompilation", "IPA Entitlements", "Hardcoded Secret Finder"],
    icon: "Smartphone",
    accentColor: "#ec4899",
    stats: { label: "Mobile Engine", value: "iOS + Android" },
  },
  {
    id: "platform-14-exploitability",
    name: "Exploitability AI Platform",
    codeName: "Platform 14",
    pillar: "cyber-defense",
    categoryLabel: "Autonomous Exploit Verification Engine",
    description: "AI-driven weaponization verification, automated proof-of-concept (PoC) generation, EPSS correlation index, and true exploitability assessment.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://14-exploitability-platform.vercel.app",
    localPort: 3014,
    localPath: "platforms/14-exploitability-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/14-exploitability-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "EPSS Model", "PoC Generator"],
    features: ["Automated PoC Generator", "EPSS Correlator", "Memory Corrupter", "WAF Bypass Engine"],
    icon: "Cpu",
    accentColor: "#f59e0b",
    stats: { label: "EPSS Precision", value: "96.5%" },
  },
  {
    id: "platform-15-threat-modeling",
    name: "Threat Modeling Suite",
    codeName: "Platform 15",
    pillar: "cyber-defense",
    categoryLabel: "Architecture & STRIDE Attack Modeling",
    description: "Cloud infrastructure graph mapping, automated STRIDE threat matrix generation, Mitre ATT&CK correlation, and multi-vector attack path simulation.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://15-threat-modeling-platform.vercel.app",
    localPort: 3015,
    localPath: "platforms/15-threat-modeling-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/15-threat-modeling-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "STRIDE Engine", "Mitre Matrix"],
    features: ["STRIDE AI Engine", "Cloud Architecture DAG", "Mitre ATT&CK Graph", "Risk Score Index"],
    icon: "Compass",
    accentColor: "#10b981",
    stats: { label: "Modeling Health", value: "99.7%" },
  },
  {
    id: "platform-16-malware",
    name: "CERBERUS-RE",
    codeName: "Platform 16",
    pillar: "cyber-defense",
    categoryLabel: "Autonomous Malware Analysis & Reverse Eng",
    description: "Deep symbolic execution, automated deobfuscation, Ghidra decompilation, dynamic execution sandbox, YARA rule generation, and C2 endpoint extraction.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://16-malware-analysis-platform.vercel.app",
    localPort: 3016,
    localPath: "platforms/16-malware-analysis-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/16-malware-analysis-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "Ghidra Decompiler", "YARA Rule Gen"],
    features: ["Dynamic Sandbox", "Ghidra Decompiler", "CFG Visualizer", "C2 Telemetry Extractor"],
    icon: "Bug",
    accentColor: "#ef4444",
    stats: { label: "Telemetry Stream", value: "8,420 ev/s" },
  },
  {
    id: "platform-17-ransomware",
    name: "Aegis Recovery",
    codeName: "Platform 17",
    pillar: "cyber-defense",
    categoryLabel: "Ransomware Recovery & Cyber Resilience",
    description: "Autonomous cryptographic feasibility analysis, immutable WORM S3 snapshot vaults, blast-radius DAG computation, and clean validation recovery sandbox.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://17-ransomware-recovery-platform.vercel.app",
    localPort: 3017,
    localPath: "platforms/17-ransomware-recovery-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/17-ransomware-recovery-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "WORM S3 Vault", "Crypto Engine"],
    features: ["WORM S3 Vault", "Crypto Feasibility Engine", "Blast Radius DAG", "Safe Sandbox Recovery"],
    icon: "ShieldCheck",
    accentColor: "#059669",
    stats: { label: "Resilience Score", value: "98.9%" },
  },
  {
    id: "platform-18-integration",
    name: "Unified Integration Layer",
    codeName: "Platform 18",
    pillar: "cyber-defense",
    categoryLabel: "Cross-Platform Orchestration & Telemetry",
    description: "Unified cross-platform telemetry gateway, gRPC heartbeat streaming, shared IOC lake, cross-platform playbooks, and central SOC dashboard.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://18-unified-integration-layer.vercel.app",
    localPort: 3018,
    localPath: "platforms/18-unified-integration-layer",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/18-unified-integration-layer",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "gRPC Heartbeat", "Unified IOC Lake"],
    features: ["Telemetry Data Lake", "Cross-Platform SOAR", "gRPC Mesh Stream", "Central SOC Dashboard"],
    icon: "Radio",
    accentColor: "#6366f1",
    stats: { label: "Connected Nodes", value: "15 Platforms" },
  },
  {
    id: "platform-19-cloud",
    name: "AXIOM Cloud Security",
    codeName: "Platform 19",
    pillar: "cyber-defense",
    categoryLabel: "Multi-Cloud PenTest & Attack Path Engine",
    description: "Multi-cloud attack path analysis, IAM privilege escalation graphing, CSPM posture evaluation, and authorized penetration testing across AWS, Azure, GCP, and K8s.",
    badge: "Platform",
    status: "ONLINE",
    vercelUrl: "https://19-cloud-security-platform.vercel.app",
    localPort: 3019,
    localPath: "platforms/19-cloud-security-platform",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/platforms/19-cloud-security-platform",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "AWS/GCP/Azure SDK", "Attack Graph"],
    features: ["Multi-Cloud Attack Graph", "IAM Privilege Escalator", "K8s RBAC Correlator", "CSPM Compliance"],
    icon: "CloudRain",
    accentColor: "#0284c7",
    stats: { label: "Throughput", value: "7,890 ev/s" },
  },
  {
    id: "aegis-strike-pentest",
    name: "Expedite Strike / Aegis Strike",
    codeName: "Strike Engine v2.0",
    pillar: "cyber-defense",
    categoryLabel: "Autonomous Penetration Testing Controller",
    description: "Autonomous pentesting engine interfacing directly with Metasploit, Nmap network scanning, OWASP ZAP automated triggers, and verified findings generator.",
    badge: "AI Engine",
    status: "PROD_ACTIVE",
    vercelUrl: "https://expedite-consults.vercel.app/connectin",
    mirrorVercelUrl: "https://backend-theta-pink-81.vercel.app",
    localPort: 3001,
    localPath: "platforms/aegis-strike/expedite-strike-master",
    githubRepo: "Danquah12/expedite-strike",
    githubUrl: "https://github.com/Danquah12/expedite-strike",
    techStack: ["Node.js Express", "Metasploit RPC", "Nmap Scanner", "ZAP Connector", "Python"],
    features: ["Autonomous Attack Loops", "Metasploit RPC Bridge", "Nmap Scanner Core", "Executive Report Gen"],
    icon: "Crosshair",
    accentColor: "#dc2626",
    stats: { label: "Engine State", value: "v2.0 Standalone" },
  },

  // ==========================================
  // PILLAR 2: CORE ENTERPRISE PORTALS & GATEWAYS
  // ==========================================
  {
    id: "expedite-consults-core",
    name: "Expedite Consults Enterprise",
    codeName: "Flagship Portal",
    pillar: "enterprise-portals",
    categoryLabel: "Enterprise Cybersecurity Advisory & Hub",
    description: "Flagship cybersecurity consulting hub, Sanity CMS intelligence, 24/7 Incident response intake, digital campus launcher, and corporate governance.",
    badge: "Enterprise",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app",
    customDomain: "https://www.expediteconsults.com",
    localPort: 3000,
    localPath: "expedite-consults",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults",
    techStack: ["Next.js 16", "Turbopack", "Sanity CMS", "Tailwind 4", "NextAuth v5"],
    features: ["Sanity Intelligence", "24/7 Incident Dispatch", "Free Assessment Tool", "Global Copilot AI"],
    icon: "Shield",
    accentColor: "#3b82f6",
    stats: { label: "Production Tier", value: "Enterprise" },
  },
  {
    id: "sphera-portal",
    name: "Sphera Client Portal",
    codeName: "Client Gateway",
    pillar: "enterprise-portals",
    categoryLabel: "High-Touch Enterprise Client Portal",
    description: "Enterprise client portal featuring Prisma ORM integration, real-time Pusher alerts, client asset governance, and SLA ticket resolution.",
    badge: "Portal",
    status: "ONLINE",
    vercelUrl: "https://sphera-portal.vercel.app",
    localPort: 3004,
    localPath: "expedite-consults/sphera-portal",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/sphera-portal",
    techStack: ["Next.js 16", "Prisma ORM", "Pusher WebSockets", "UploadThing", "Zustand"],
    features: ["Client SLA Tracking", "Live Pusher Alerts", "Secure File Vault", "Prisma Database Sync"],
    icon: "Globe2",
    accentColor: "#8b5cf6",
    stats: { label: "Database Layer", value: "Prisma Active" },
  },
  {
    id: "veritaslens-ai",
    name: "VeritasLens AI Media Intelligence",
    codeName: "VeritasLens",
    pillar: "enterprise-portals",
    categoryLabel: "Autonomous OSINT & Media Forensics",
    description: "Real-time media intelligence engine, deepfake forensics, OSINT threat feeds, bias scoring, and SQLite automated scraping pipelines.",
    badge: "AI Engine",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/veritaslens",
    internalRoute: "/veritaslens",
    localPath: "expedite-consults/app/veritaslens",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/veritaslens",
    techStack: ["Next.js 16", "Python Scrapers", "SQLite Database", "NLP Classifier", "OSINT Feeds"],
    features: ["Real-time Misinfo Hunter", "Deepfake Forensics", "SQLite Telemetry", "Automated Scrapers"],
    icon: "Eye",
    accentColor: "#06b6d4",
    stats: { label: "Scraper Status", value: "Pipeline Live" },
  },
  {
    id: "cr-process-portal",
    name: "ConnectSuite / Change Request Portal",
    codeName: "ConnectSuite",
    pillar: "enterprise-portals",
    categoryLabel: "ITIL Governance & ServiceNow / Exchange",
    description: "ITIL Change Request workflow automation, ServiceNow bi-directional synchronization, Exchange approval routing, and audit trace records.",
    badge: "Portal",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/cr",
    internalRoute: "/cr",
    localPath: "expedite-consults/app/(cr-portal)",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/(cr-portal)",
    techStack: ["Next.js 16", "Tailwind 4", "ServiceNow Webhooks", "Exchange API", "Audit Logger"],
    features: ["Change Advisory Board Workflow", "ServiceNow Integration", "Immutable Audit Trace", "Exchange Routing"],
    icon: "FileCheck2",
    accentColor: "#f59e0b",
    stats: { label: "Compliance", value: "ITIL v4" },
  },
  {
    id: "incident-response-soc",
    name: "24/7 Incident Response SOC",
    codeName: "SOC Dispatch",
    pillar: "enterprise-portals",
    categoryLabel: "Emergency Incident Triage & SOC Dispatch",
    description: "Emergency incident response triage intake, real-time threat severity calculators, SOC responder escalation dispatch, and immediate containment runbooks.",
    badge: "Portal",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/incident-response",
    internalRoute: "/incident-response",
    localPath: "expedite-consults/app/(user)/incident-response",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/(user)/incident-response",
    techStack: ["Next.js 16", "Tailwind 4", "Resend API", "Severity Scorer", "SOC Dispatch"],
    features: ["Emergency Hotline Intake", "Severity Matrix Calculator", "Automated Runbooks", "Encrypted Form"],
    icon: "PhoneCall",
    accentColor: "#ef4444",
    stats: { label: "SLA Response", value: "< 15 Mins" },
  },

  // ==========================================
  // PILLAR 3: SPHERA SOCIAL & COLLABORATIVE STUDIO ECOSYSTEM
  // ==========================================
  {
    id: "sphera-social",
    name: "Sphera Social Hub",
    codeName: "Sphera Social",
    pillar: "sphera-ecosystem",
    categoryLabel: "Verified Cybersecurity Social Network",
    description: "Decentralized professional social platform for verified cybersecurity practitioners, secure message channels, peer reviews, and reputation graphs.",
    badge: "Vercel Live",
    status: "ONLINE",
    vercelUrl: "https://sphera-social.vercel.app",
    githubRepo: "Danquah12/sphera-social",
    githubUrl: "https://github.com/Danquah12/sphera-social",
    techStack: ["Next.js", "React 19", "Tailwind CSS", "FastAPI Relay"],
    features: ["Verified Practitioner Feeds", "Encrypted Messaging", "Guild Channels", "Reputation Scoring"],
    icon: "Share2",
    accentColor: "#a855f7",
    stats: { label: "Deployment", value: "Vercel Live" },
  },
  {
    id: "sphera-studio",
    name: "Sphera Studio (15 Worlds & Vault)",
    codeName: "Sphera Studio",
    pillar: "sphera-ecosystem",
    categoryLabel: "Creative Simulation Workbench & Studio",
    description: "Luxury 3-column ecosystem overhaul, 3-mode theme engine, command palette, live stages, zero-trust security enclave, and 15 interactive cyber simulation worlds.",
    badge: "Vercel Live",
    status: "ONLINE",
    vercelUrl: "https://sphera-studio.vercel.app",
    githubRepo: "Danquah12/sphera-studio",
    githubUrl: "https://github.com/Danquah12/sphera-studio",
    techStack: ["Next.js", "Three.js / Canvas", "Tailwind 4", "Zero-Trust Enclave"],
    features: ["15 Simulation Worlds", "Zero-Trust Enclave", "Command Palette", "3-Mode Theme Engine"],
    icon: "Sparkles",
    accentColor: "#ec4899",
    stats: { label: "Simulation Worlds", value: "15 Worlds" },
  },
  {
    id: "sphera-frontend",
    name: "Sphera Frontend Modular Suite",
    codeName: "Sphera FE Suite",
    pillar: "sphera-ecosystem",
    categoryLabel: "High-Performance Modular Web Client",
    description: "Modular, high-performance HTML5/CSS3/JavaScript client suite with IRGF compliance integration and rapid micro-frontend modules.",
    badge: "Vercel Live",
    status: "ONLINE",
    vercelUrl: "https://sphera-frontend.vercel.app",
    mirrorVercelUrl: "https://sphera-frontend-q8dx.vercel.app",
    githubRepo: "Danquah12/sphera-frontend",
    githubUrl: "https://github.com/Danquah12/sphera-frontend",
    techStack: ["Modern JS", "Tailwind CSS", "Micro-Frontend", "IRGF Compliance"],
    features: ["Modular Component Shell", "Ultra-Low Latency", "IRGF Standardized", "Mobile First"],
    icon: "Layout",
    accentColor: "#8b5cf6",
    stats: { label: "Frontend State", value: "Live Multi-Deploy" },
  },
  {
    id: "sphera-frontend-irgf",
    name: "Sphera Frontend (IRGF Compliance Node)",
    codeName: "Sphera IRGF Node",
    pillar: "sphera-ecosystem",
    categoryLabel: "Global IRGF Standardized Portal",
    description: "Dedicated IRGF standardized frontend interface providing high-assurance audit trails, cryptographic verification, and compliance verification.",
    badge: "Vercel Live",
    status: "ONLINE",
    vercelUrl: "https://sphera-frontend-irgf.vercel.app",
    githubRepo: "Danquah12/sphera-frontend",
    githubUrl: "https://github.com/Danquah12/sphera-frontend",
    techStack: ["Next.js", "IRGF Node", "Tailwind CSS"],
    features: ["IRGF Verification", "Audit Trails", "Compliant Node", "Sub-Second Delivery"],
    icon: "Layers",
    accentColor: "#38bdf8",
    stats: { label: "Standard", value: "IRGF Certified" },
  },
  {
    id: "sphera-backend",
    name: "Sphera Backend Microservice",
    codeName: "Sphera Backend",
    pillar: "sphera-ecosystem",
    categoryLabel: "FastAPI Enterprise API Engine",
    description: "High-performance Python FastAPI backend microservice managing authentication, user state synchronization, event streaming, and secure data storage.",
    badge: "Vercel Live",
    status: "ONLINE",
    vercelUrl: "https://sphera-backend-alpha.vercel.app",
    mirrorVercelUrl: "https://backend-theta-pink-81.vercel.app",
    localPort: 8000,
    githubRepo: "Danquah12/sphera-backend",
    githubUrl: "https://github.com/Danquah12/sphera-backend",
    techStack: ["Python 3.11", "FastAPI", "Uvicorn", "Pydantic v2", "PostgreSQL"],
    features: ["FastAPI Asynchronous Engine", "JWT Token Auth", "Telemetry Endpoints", "Postgres Connection Pool"],
    icon: "Server",
    accentColor: "#10b981",
    stats: { label: "Backend Core", value: "FastAPI v0.110" },
  },
  {
    id: "sphera-platform",
    name: "Sphera Unified Platform Umbrella",
    codeName: "Sphera Platform",
    pillar: "sphera-ecosystem",
    categoryLabel: "Enterprise Unified Platform Umbrella",
    description: "Global umbrella portal coordinating the entire Sphera ecosystem, shared session identity, and cross-application federated navigation.",
    badge: "Vercel Live",
    status: "ONLINE",
    vercelUrl: "https://sphera-platform.vercel.app",
    mirrorVercelUrl: "https://sphera-phi.vercel.app",
    githubRepo: "Danquah12/sphera-frontend",
    githubUrl: "https://github.com/Danquah12/sphera-frontend",
    techStack: ["Next.js", "Federated Shell", "Tailwind CSS", "Vercel Edge"],
    features: ["Federated App Routing", "Global Identity Sync", "Unified Navigation", "Edge CDN Cached"],
    icon: "Orbit",
    accentColor: "#3b82f6",
    stats: { label: "Architecture", value: "Federated Mesh" },
  },

  // ==========================================
  // PILLAR 4: CONNECTIN PROFESSIONAL SUPER APP
  // ==========================================
  {
    id: "connectin-os",
    name: "ConnectIn Professional Super App",
    codeName: "ConnectIn OS",
    pillar: "connectin-os",
    categoryLabel: "Unified Professional Operating System",
    description: "30-Pillar Enterprise Professional OS: Personalized Feed, AI Daily Threat Pulse, 16-Product Commercial Marketplace, Live Jobs Pipeline, Learning Labs, and Defense Labs.",
    badge: "SuperApp",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/connectin",
    internalRoute: "/connectin",
    localPath: "expedite-consults/app/connectin",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/connectin",
    techStack: ["Next.js 16", "Turbopack", "Tailwind 4", "Zustand State", "Lucide Icons"],
    features: ["30 Roadmap Pillars", "Marketplace with 16 Products", "AI Daily Threat Radar", "Career Learning Paths"],
    icon: "Briefcase",
    accentColor: "#0284c7",
    stats: { label: "Roadmap Pillars", value: "30 Pillars" },
  },
  {
    id: "connectin-auth-iam",
    name: "ConnectIn IAM & Security Center",
    codeName: "ConnectIn IAM",
    pillar: "connectin-os",
    categoryLabel: "Role-Aware 2FA Authentication & 4-Eyes Governance",
    description: "Multi-factor authentication (Email/SMS 2FA), role-aware personas redirection, live SOC threat alert engine, active session telemetry, and 4-Eyes admin governance.",
    badge: "SuperApp",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/connectin-login",
    internalRoute: "/connectin-login",
    localPath: "expedite-consults/app/connectin-login",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/connectin-login",
    techStack: ["Next.js 16", "SMS/Email 2FA", "RBAC Engine", "Session Inspector"],
    features: ["2FA Verification Flow", "Personas Switcher", "SOC Threat Alerts", "Admin 4-Eyes Approval"],
    icon: "ShieldAlert",
    accentColor: "#ef4444",
    stats: { label: "Security Tier", value: "2FA + SOC Enclave" },
  },
  {
    id: "connectin-media-labs",
    name: "ConnectIn Media & Defense Labs",
    codeName: "Defense Labs",
    pillar: "connectin-os",
    categoryLabel: "Interactive Watch, Transcripts & Cyber Sandbox",
    description: "Interactive side-by-side sandbox video player, AI transcript search, chapters, B2B commerce funnels, token-gated guilds, and interactive cyber defense labs.",
    badge: "SuperApp",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/connectin",
    internalRoute: "/connectin?tab=media",
    localPath: "expedite-consults/app/connectin",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/connectin",
    techStack: ["Next.js 16", "Video Player", "AI Transcript Parser", "Defense Sandbox"],
    features: ["Interactive Video Player", "AI Transcript Search", "Token-Gated Guilds", "Inbound Recruiter Bounties"],
    icon: "Video",
    accentColor: "#6366f1",
    stats: { label: "Interactive Labs", value: "Live Sandbox" },
  },
  {
    id: "connectin-ai-copilot",
    name: "ConnectIn AI Assistant & Knowledge Ranker",
    codeName: "ConnectIn Copilot",
    pillar: "connectin-os",
    categoryLabel: "Autonomous Knowledge Search & Action Jumpers",
    description: "Unified AI Assistant with site-wide semantic ranking, African Student Association (ASA) knowledge, automated resume feedback, and instant action jumpers.",
    badge: "AI Engine",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/connectin",
    internalRoute: "/connectin",
    localPath: "expedite-consults/components/global-copilot",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/components/global-copilot",
    techStack: ["Next.js 16", "Semantic Search", "Vector Embeddings", "Prompt Engine"],
    features: ["Multi-Domain Knowledge", "Site-Wide Semantic Ranker", "1-Click Action Jumpers", "Context Awareness"],
    icon: "Bot",
    accentColor: "#10b981",
    stats: { label: "Intelligence Index", value: "Website-Wide" },
  },

  // ==========================================
  // PILLAR 5: CAMPUS & STUDENT OPERATING PLATFORM
  // ==========================================
  {
    id: "campus-towson-sync",
    name: "CampusSync / TowsonSync Platform",
    codeName: "CampusSync",
    pillar: "campus-ecosystem",
    categoryLabel: "18-Module Modular Campus Operating Platform",
    description: "Complete campus ecosystem: MY DAY command center, Canvas Radar, Digital Tiger OneCard Wallet, SafeWalk Escort, Live Density IoT, NOAA Weather, and Alumni Mentorship.",
    badge: "SuperApp",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/campus",
    internalRoute: "/campus",
    localPath: "expedite-consults/app/campus",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/campus",
    techStack: ["Next.js 16", "NOAA Weather API", "Canvas Integration", "Density IoT", "Framer Motion"],
    features: ["MY DAY Command Center", "Digital OneCard Wallet", "Canvas Sync Radar", "SafeWalk Escort"],
    icon: "GraduationCap",
    accentColor: "#f59e0b",
    stats: { label: "Integrated Modules", value: "18 Modules" },
  },
  {
    id: "tiger-orbit-360",
    name: "TigerOrbit 360 & Live Campus Map",
    codeName: "TigerOrbit 360",
    pillar: "campus-ecosystem",
    categoryLabel: "Live Location Circles, Indoor Plans & TUPD GPS",
    description: "Real-time Life360-style location circles for student groups, multi-floor indoor building plans, Tiger Ride real-time GPS tracking, and TUPD safety escort layer.",
    badge: "SuperApp",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/campus",
    internalRoute: "/campus?tab=map",
    localPath: "expedite-consults/app/campus",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/campus",
    techStack: ["Next.js 16", "Leaflet / Maps", "GeoJSON", "Real-Time Telemetry"],
    features: ["Life360 Location Circles", "Indoor Floorplans", "Tiger Ride GPS Tracker", "TUPD Emergency Beacons"],
    icon: "MapPin",
    accentColor: "#d97706",
    stats: { label: "GPS Telemetry", value: "Sub-Second" },
  },
  {
    id: "campus-student-onboarding",
    name: "Student Verification & Onboarding",
    codeName: "Campus Onboarding",
    pillar: "campus-ecosystem",
    categoryLabel: "Student Identity & Single Sign-On Gateway",
    description: "Secure student credential verification, university Single Sign-On (SSO) gateway, course hydration engine, and digital campus passport issuance.",
    badge: "Portal",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/campus/login",
    internalRoute: "/campus/login",
    localPath: "expedite-consults/app/campus/login",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/app/campus/login",
    techStack: ["Next.js 16", "SSO Auth", "Passport Minting", "Course Hydration"],
    features: ["Instant Student Verification", "Digital Campus Passport", "Course Schedule Hydration", "RBAC Access"],
    icon: "UserCheck",
    accentColor: "#e11d48",
    stats: { label: "Auth Flow", value: "Verified SSO" },
  },

  // ==========================================
  // PILLAR 6: TALENT, COMMERCE & STANDALONE APPS
  // ==========================================
  {
    id: "careerorbit-standalone",
    name: "CareerOrbit Standalone",
    codeName: "CareerOrbit",
    pillar: "talent-commerce",
    categoryLabel: "Autonomous Cyber Talent & Resume AI Engine",
    description: "Enterprise standalone cyber talent platform with AI resume parsing, automated skill gap analysis, recruiter matchmaking, and live US market salary indexing.",
    badge: "Vercel Live",
    status: "STANDALONE",
    vercelUrl: "https://careerorbit-standalone.vercel.app",
    mirrorVercelUrl: "https://careerorbit-mu.vercel.app",
    localPort: 3000,
    localPath: "expedite-consults/careerorbit",
    githubRepo: "Danquah12/careerorbit-standalone",
    githubUrl: "https://github.com/Danquah12/careerorbit-standalone",
    techStack: ["Next.js 16", "React 19", "Tailwind 4", "Resume AI NLP"],
    features: ["AI Resume Parser", "Skill Gap Indexer", "US Market Salary Bands", "Recruiter Matchmaking"],
    icon: "Briefcase",
    accentColor: "#3b82f6",
    stats: { label: "Market Focus", value: "US Cyber Talent" },
  },
  {
    id: "bazaar-marketplace",
    name: "BAZAAR Verified Commerce",
    codeName: "BAZAAR",
    pillar: "talent-commerce",
    categoryLabel: "AI-Powered Verified Marketplace with eBay C2C",
    description: "Autonomous verified goods marketplace featuring eBay C2C API integration, AI fraud detection, escrow verification, and instant seller storefronts.",
    badge: "Vercel Live",
    status: "STANDALONE",
    vercelUrl: "https://bazaar-standalone.vercel.app",
    githubRepo: "Danquah12/bazaar-standalone",
    githubUrl: "https://github.com/Danquah12/bazaar-standalone",
    techStack: ["Next.js", "eBay C2C API", "AI Fraud Shield", "Tailwind CSS"],
    features: ["eBay API Integration", "Escrow Protection", "AI Price Suggester", "Seller Storefronts"],
    icon: "ShoppingBag",
    accentColor: "#f43f5e",
    stats: { label: "Commerce Engine", value: "eBay C2C Ready" },
  },
  {
    id: "axiom-webmail-teams",
    name: "Axiom Webmail & Teams Suite",
    codeName: "Axiom Connect",
    pillar: "talent-commerce",
    categoryLabel: "Encrypted Mail, Modern Action Ribbon & Video Meetings",
    description: "Complete encrypted corporate communication suite with Zoho/Outlook-style Modern Action Ribbon (Sweep, Quick Steps), Viva Insights, calendar scheduling, and WebRTC video meetings.",
    badge: "Integrated",
    status: "ONLINE",
    vercelUrl: "https://expedite-consults.vercel.app/mail",
    internalRoute: "/mail",
    localPort: 3001,
    localPath: "expedite-consults/mail-platform/frontend",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults/tree/main/mail-platform",
    techStack: ["Next.js 14", "Python FastAPI Backend", "PostgreSQL", "Redis", "MinIO S3", "Mailpit"],
    features: ["Outlook Action Ribbon", "Sweep & Quick Steps", "WebRTC Video Meetings", "End-to-End Encrypted"],
    icon: "Mail",
    accentColor: "#0284c7",
    stats: { label: "Encryption", value: "End-to-End" },
  },

  // ==========================================
  // PILLAR 7: GLOBAL SOCIAL IMPACT & SPECIALTY INITIATIVES
  // ==========================================
  {
    id: "csrta-ewaste-initiative",
    name: "CSRTA E-Waste National Initiative",
    codeName: "CSRTA E-Waste",
    pillar: "social-impact",
    categoryLabel: "National Electronic Waste Sustainability Portal",
    description: "Official sustainability research and survey platform analyzing electronic waste lifecycle management, environmental compliance, and circular economy tracking.",
    badge: "Impact",
    status: "PROD_ACTIVE",
    vercelUrl: "https://csrtainitiative.org",
    mirrorVercelUrl: "https://e-waste-csrta.vercel.app",
    customDomain: "https://csrtainitiative.org",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults",
    techStack: ["Next.js", "React", "Survey Engine", "Analytics Dashboard"],
    features: ["National Survey Pipeline", "E-Waste Lifecycle Metric", "Compliance Scorecard", "Public Data Portal"],
    icon: "Recycle",
    accentColor: "#10b981",
    stats: { label: "Live Domain", value: "csrtainitiative.org" },
  },
  {
    id: "skillhands-client",
    name: "SkillHands Client Portal",
    codeName: "SkillHands Client",
    pillar: "social-impact",
    categoryLabel: "Verified Vocational & Skills Marketplace Frontend",
    description: "Decentralized vocational skills exchange client matching certified tradespeople and technical specialists with community projects.",
    badge: "Impact",
    status: "STANDALONE",
    vercelUrl: "https://skillhands-client.vercel.app",
    githubRepo: "Danquah12/skillhands-client",
    githubUrl: "https://github.com/Danquah12/skillhands-client",
    techStack: ["Next.js Client", "Tailwind CSS", "React 19"],
    features: ["Tradesperson Verification", "Direct Micro-Contracts", "Client Review Mesh", "Skills Portfolio"],
    icon: "Hammer",
    accentColor: "#eab308",
    stats: { label: "Deployment", value: "Vercel Live" },
  },
  {
    id: "skillhands-server",
    name: "SkillHands API Backend Server",
    codeName: "SkillHands Server",
    pillar: "social-impact",
    categoryLabel: "Vocational Network API & Database Engine",
    description: "High-performance Node.js Express backend API providing contractor matching algorithms, secure escrow ledger, and profile indexing.",
    badge: "Impact",
    status: "STANDALONE",
    vercelUrl: "https://skillhands-server.vercel.app",
    githubRepo: "Danquah12/skillhands-server",
    githubUrl: "https://github.com/Danquah12/skillhands-server",
    techStack: ["Node Express", "MongoDB Atlas", "JWT Auth", "REST API"],
    features: ["Contractor Matching Engine", "Escrow Ledger", "RESTful Endpoints", "MongoDB Integration"],
    icon: "Server",
    accentColor: "#f59e0b",
    stats: { label: "API Core", value: "Node Express" },
  },
  {
    id: "tu-housing-portal",
    name: "TU Housing & Off-Campus Platform",
    codeName: "TU Housing",
    pillar: "social-impact",
    categoryLabel: "Student Housing & Roommate Verification Network",
    description: "Dedicated off-campus housing discovery portal with verified student landlords, roommate compatibility matching, sublease agreements, and interactive map listings.",
    badge: "Impact",
    status: "STANDALONE",
    vercelUrl: "https://tuhousing.vercel.app",
    githubRepo: "Danquah12/expedite-consults",
    githubUrl: "https://github.com/Danquah12/expedite-consults",
    techStack: ["Next.js", "Leaflet Maps", "Roommate AI", "Tailwind CSS"],
    features: ["Verified Student Listings", "Roommate Matching AI", "Sublease Contracts", "Interactive Map Search"],
    icon: "Home",
    accentColor: "#f97316",
    stats: { label: "Deployment", value: "tuhousing.vercel.app" },
  },
];
