#!/usr/bin/env bash
# =============================================================================
# AEGIS Platform — Deployment Script
# =============================================================================
# Usage:
#   ./deploy.sh              Build & start all services, run health checks
#   ./deploy.sh --stop       Stop all services
#   ./deploy.sh --restart    Restart all services (stop → build → start)
#   ./deploy.sh --logs       Tail logs from every container
# =============================================================================
set -euo pipefail

# ── Colour helpers ───────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m' # No Colour

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[  OK]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[FAIL]${NC}  $*"; }
header()  { echo -e "\n${BOLD}════════════════════════════════════════════════════════════${NC}"; \
            echo -e "${BOLD}  $*${NC}"; \
            echo -e "${BOLD}════════════════════════════════════════════════════════════${NC}\n"; }

# ── Project root (directory this script lives in) ────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${SCRIPT_DIR}"

# ── Domain ───────────────────────────────────────────────────────────────────
DOMAIN="aegis.expediteconsults.com"

# ── Service registry ────────────────────────────────────────────────────────
# Format: "CODENAME:port:path:description"
SERVICES=(
    "COMMAND:9000:/:Launchpad"
    "WATCHTOWER:9001:/watchtower:SOC Home"
    "BASTION:9021:/bastion:Main SOC"
    "SPECTRE:9012:/spectre:External Pentest"
    "VIPER:9013:/viper:Red Team Ops"
    "TRIDENT:9014:/trident:Red Team Suite"
    "RAMPART:9015:/rampart:Cyber Defence"
    "ECHELON:9016:/echelon:Specialised Ops"
    "BULWARK:9017:/bulwark:GRC"
    "CORSAIR:9018:/corsair:DFIR"
    "NEXUS:9019:/nexus:Platform"
    "LEDGER:9020:/ledger:Reports"
)

# =============================================================================
# Pre-flight checks
# =============================================================================
check_prerequisites() {
    header "Pre-flight Checks"

    # Docker
    if command -v docker &>/dev/null; then
        success "Docker found: $(docker --version)"
    else
        error "Docker is not installed. Please install Docker first."
        echo -e "  → https://docs.docker.com/engine/install/"
        exit 1
    fi

    # docker-compose (v1) or docker compose (v2 plugin)
    if command -v docker-compose &>/dev/null; then
        COMPOSE_CMD="docker-compose"
        success "docker-compose found: $(docker-compose --version)"
    elif docker compose version &>/dev/null 2>&1; then
        COMPOSE_CMD="docker compose"
        success "docker compose (plugin) found: $(docker compose version)"
    else
        error "docker-compose is not installed. Please install it first."
        echo -e "  → https://docs.docker.com/compose/install/"
        exit 1
    fi

    # Docker daemon running?
    if docker info &>/dev/null; then
        success "Docker daemon is running"
    else
        error "Docker daemon is not running. Start it with: sudo systemctl start docker"
        exit 1
    fi
}

# =============================================================================
# Directory scaffolding
# =============================================================================
create_directories() {
    header "Creating Directories"

    local dirs=("reports" "data" "certs")
    for dir in "${dirs[@]}"; do
        target="${PROJECT_DIR}/${dir}"
        if [[ -d "${target}" ]]; then
            info "Directory already exists: ${dir}/"
        else
            mkdir -p "${target}"
            success "Created: ${dir}/"
        fi
    done
}

# =============================================================================
# Bootstrap .env.production
# =============================================================================
create_env_file() {
    header "Environment Configuration"

    local env_file="${PROJECT_DIR}/.env.production"

    if [[ -f "${env_file}" ]]; then
        info ".env.production already exists — skipping (delete it to regenerate)"
        return
    fi

    info "Generating .env.production with sensible defaults …"

    cat > "${env_file}" <<'ENVEOF'
# =============================================================================
# AEGIS Platform — Production Environment Variables
# =============================================================================
# Generated by deploy.sh — edit as needed before first launch.
# =============================================================================

# ── General ──────────────────────────────────────────────────────────────────
COMPOSE_PROJECT_NAME=aegis
AEGIS_ENV=production
AEGIS_DEBUG=false
AEGIS_LOG_LEVEL=INFO

# ── Networking ───────────────────────────────────────────────────────────────
AEGIS_HOST=0.0.0.0
AEGIS_EXTERNAL_URL=https://aegis.expediteconsults.com

# ── Database ─────────────────────────────────────────────────────────────────
POSTGRES_HOST=aegis-db
POSTGRES_PORT=5432
POSTGRES_DB=aegis
POSTGRES_USER=aegis
POSTGRES_PASSWORD=CHANGE_ME_BEFORE_PRODUCTION

# ── Redis ────────────────────────────────────────────────────────────────────
REDIS_HOST=aegis-redis
REDIS_PORT=6379

# ── Secrets (rotate before production!) ──────────────────────────────────────
AEGIS_SECRET_KEY=CHANGE_ME_BEFORE_PRODUCTION
AEGIS_JWT_SECRET=CHANGE_ME_BEFORE_PRODUCTION

# ── Report storage ───────────────────────────────────────────────────────────
REPORTS_DIR=/app/reports
DATA_DIR=/app/data

# ── SSL (populated by certbot later) ─────────────────────────────────────────
# SSL_CERT_PATH=/etc/letsencrypt/live/yourdomain/fullchain.pem
# SSL_KEY_PATH=/etc/letsencrypt/live/yourdomain/privkey.pem
ENVEOF

    success ".env.production created"
    warn "Review ${env_file} and change default passwords before going live!"
}

# =============================================================================
# Build
# =============================================================================
build_services() {
    header "Building Docker Images"

    info "Running: ${COMPOSE_CMD} build"
    ${COMPOSE_CMD} --env-file "${PROJECT_DIR}/.env.production" build
    success "Build complete"
}

# =============================================================================
# Start
# =============================================================================
start_services() {
    header "Starting Services"

    info "Running: ${COMPOSE_CMD} up -d"
    ${COMPOSE_CMD} --env-file "${PROJECT_DIR}/.env.production" up -d
    success "All containers launched"
}

# =============================================================================
# Stop
# =============================================================================
stop_services() {
    header "Stopping Services"

    info "Running: ${COMPOSE_CMD} down"
    ${COMPOSE_CMD} --env-file "${PROJECT_DIR}/.env.production" down
    success "All containers stopped"
}

# =============================================================================
# Logs
# =============================================================================
tail_logs() {
    header "Tailing Logs (Ctrl+C to exit)"
    ${COMPOSE_CMD} --env-file "${PROJECT_DIR}/.env.production" logs -f --tail=100
}

# =============================================================================
# Health checks
# =============================================================================
health_check() {
    header "Health Checks  ─  ${DOMAIN}"

    local wait_secs=15
    info "Waiting ${wait_secs}s for services to initialise …"
    sleep "${wait_secs}"

    # Table header
    printf "\n"
    printf "  ${BOLD}%-12s  %-8s  %-16s  %-14s  %s${NC}\n" \
           "CODENAME" "PORT" "PATH" "STATUS" "DESCRIPTION"
    printf "  %-12s  %-8s  %-16s  %-14s  %s\n" \
           "────────────" "────────" "────────────────" "──────────────" "──────────────"

    local pass=0
    local fail=0

    for entry in "${SERVICES[@]}"; do
        IFS=':' read -r codename port path desc <<< "${entry}"

        # Attempt a lightweight curl against localhost on the service port
        http_code=$(curl -s -o /dev/null -w "%{http_code}" \
                         --max-time 5 "http://localhost:${port}${path}" 2>/dev/null || echo "000")

        if [[ "${http_code}" =~ ^(200|301|302|304)$ ]]; then
            status="${GREEN}● UP  (${http_code})${NC}"
            ((pass++))
        else
            status="${RED}✘ DOWN(${http_code})${NC}"
            ((fail++))
        fi

        printf "  ${BOLD}%-12s${NC}  ${DIM}(:%-5s)${NC}  %-16s  $(echo -e "${status}")  ${DIM}● %s${NC}\n" \
               "${codename}" "${port}" "${path}" "" "${desc}"
    done

    printf "\n  ────────────────────────────────────────────────────────────────\n"
    printf "  ${GREEN}Passed: ${pass}${NC}  ${RED}Failed: ${fail}${NC}  Total: $(( pass + fail ))\n\n"

    if (( fail > 0 )); then
        warn "Some services failed health checks. Run '${COMPOSE_CMD} logs <service>' to investigate."
    else
        success "All services are healthy!"
    fi
}

# =============================================================================
# Summary
# =============================================================================
print_summary() {
    header "AEGIS Platform — Deployment Summary"

    local base_url="https://${DOMAIN}"

    echo -e "  ${BOLD}Domain:${NC}      ${CYAN}${DOMAIN}${NC}"
    echo -e "  ${BOLD}Access URL:${NC}  ${CYAN}${base_url}${NC}"
    echo ""

    # ── Service table ────────────────────────────────────────────────────────
    echo -e "  ${BOLD}Tactical Service Map:${NC}"
    echo ""
    printf "  ${BOLD}%-12s  %-8s  %-2s %-16s  %s${NC}\n" \
           "CODENAME" "PORT" "→" "PATH" "DESCRIPTION"
    printf "  %-12s  %-8s  %-2s %-16s  %s\n" \
           "────────────" "────────" "──" "────────────────" "──────────────"

    for entry in "${SERVICES[@]}"; do
        IFS=':' read -r codename port path desc <<< "${entry}"
        printf "  ${BOLD}%-12s${NC}  ${DIM}(:%-5s)${NC}  → %-16s  ${DIM}● %s${NC}\n" \
               "${codename}" "${port}" "${path}" "${desc}"
    done

    echo ""
    echo -e "  ${BOLD}Useful Commands:${NC}"
    echo -e "    ${CYAN}./deploy.sh --stop${NC}       Stop all services"
    echo -e "    ${CYAN}./deploy.sh --restart${NC}    Restart all services"
    echo -e "    ${CYAN}./deploy.sh --logs${NC}       Tail all container logs"
    echo -e "    ${CYAN}${COMPOSE_CMD} ps${NC}          List running containers"
    echo ""
}

# =============================================================================
# Main
# =============================================================================
main() {
    cd "${PROJECT_DIR}"

    case "${1:-}" in
        --stop)
            check_prerequisites
            stop_services
            exit 0
            ;;
        --restart)
            check_prerequisites
            stop_services
            build_services
            start_services
            health_check
            print_summary
            exit 0
            ;;
        --logs)
            check_prerequisites
            tail_logs
            exit 0
            ;;
        --help|-h)
            echo "Usage: $0 [--stop|--restart|--logs|--help]"
            exit 0
            ;;
        "")
            # Default: full deploy
            ;;
        *)
            error "Unknown flag: $1"
            echo "Usage: $0 [--stop|--restart|--logs|--help]"
            exit 1
            ;;
    esac

    header "AEGIS Platform — Deployment"
    check_prerequisites
    create_directories
    create_env_file
    build_services
    start_services
    health_check
    print_summary

    success "Deployment complete 🚀"
}

main "$@"
