"use client";

import { useState, useEffect } from "react";
import {
  GitBranch, ShieldCheck, ShieldAlert, Info, X, Target, Info as InfoIcon, Radio, RefreshCw, AlertTriangle, ExternalLink, Zap, Search, Database, Sparkles, Cpu, Layers
} from "lucide-react";

type RAGResult = {
  platform: string;
  source: string;
  finding: string;
  severity: "Critical" | "High" | "Medium";
  similarity: number;
  snippet: string;
};

const MOCK_RAG_KNOWLEDGE: Record<string, RAGResult[]> = {
  "default": [
    { platform: "05-SAST", source: "AccountController.java:27", finding: "CWE-89: SQL Injection Concatenation", severity: "Critical", similarity: 0.94, snippet: "jdbcTemplate.queryForObject(query, String.class) reaches PostgreSQL query parser directly." },
    { platform: "12-API", source: "/api/v2/orders/{id}", finding: "API1:2023: Broken Object Level Authorization (BOLA)", severity: "Critical", similarity: 0.91, snippet: "GET /api/v2/orders/10492 permits cross-tenant database record traversal." },
    { platform: "08-Container", source: "Dockerfile:2", finding: "CIS-4.1: Container Root Execution PrivEsc", severity: "High", similarity: 0.88, snippet: "Container process runs as UID=0, enabling kernel namespace breakout." },
    { platform: "07-Secrets", source: "config/stripe.ts:12", finding: "Stripe Live Secret Key Leak", severity: "Critical", similarity: 0.85, snippet: "Shannon Entropy: 7.1 bits/char. STS credential live validation confirmed." }
  ]
};

type NodeItem = {
  id: string;
  name: string;
  x: number;
  y: number;
  type: "entry" | "vulnerability" | "target" | "auth";
  vulnerability: string;
  blastRadius: "Low" | "Medium" | "High" | "Critical";
  remediation: string;
  description: string;
};

type DetailInfo = {
  title: string;
  category: string;
  what: string;
  why: string;
  risk: string;
  impact?: string;
};

type TelemetryEvent = {
  type: string;
  moduleId?: string;
  moduleName?: string;
  severity?: string;
  compromisedNodes?: string[];
  timestamp: string;
};

const CHAIN_DETAILS: Record<string, DetailInfo> = {
  "client_portal": {
    title: "Client Portal (Node 1 - Entry)",
    category: "Attack Chain Entry",
    what: "The public interface exposed to internet traffic.",
    why: "Audited to map how attackers initially interface with application routes.",
    risk: "Serves as the launching pad for prompt injections, CORS hijacking, and parameter fuzzing.",
    impact: "Low initial impact, but high propagation exposure."
  },
  "api_gateway": {
    title: "API Gateway SQLi & BOLA (Node 2 - Pivot)",
    category: "Attack Chain Pivot",
    what: "Internal route handling client queries, hosting parameter validation flaws (SQL Injection F-001 & BOLA F-004).",
    why: "Audited to check if input parameters are parsed securely prior to backend calls.",
    risk: "Attackers can manipulate database structure, bypass auth filters, or pivot deeper into Postgres DB.",
    impact: "High impact. Gateways represent centralized authorization zones."
  },
  "auth_service": {
    title: "Auth Service JWT & Cloud IAM (Node 3 - Pivot)",
    category: "Attack Chain Pivot",
    what: "Identity provider microservice hosting weak cryptographic keys (JWT weak secret F-004) and IAM/K8s RBAC tokens.",
    why: "Audited to guarantee secure tokens can only be generated by genuine system authorities.",
    risk: "Allows token forging and IAM role assumption, enabling low-level users to impersonate system admins.",
    impact: "Critical impact. Grants full control over security envelopes."
  },
  "postgres_db": {
    title: "PostgreSQL Database (Node 4 - Target)",
    category: "Attack Chain Target",
    what: "The central data repository containing sensitive PII, cardholder data, and credential tables.",
    why: "Represent the Crown Jewel target of the entire attack chain.",
    risk: "Total database theft, deletion of financial records, or configuration takeover.",
    impact: "Critical impact. Maximum blast damage."
  }
};

const ARCH_NODES: NodeItem[] = [
  {
    id: "client_portal",
    name: "Client Portal",
    x: 80,
    y: 120,
    type: "entry",
    vulnerability: "Public exposure",
    blastRadius: "Low",
    remediation: "Deploy Web Application Firewall (WAF)",
    description: "External customer web interface. Handles cookie storage and API request routing."
  },
  {
    id: "api_gateway",
    name: "API Gateway",
    x: 240,
    y: 120,
    type: "vulnerability",
    vulnerability: "SQL Injection / BOLA (CWE-89)",
    blastRadius: "High",
    remediation: "Bind parameters on database queries & enforce object-level RBAC",
    description: "Central input parser for database queries. Vulnerable to query modification and object traversal."
  },
  {
    id: "auth_service",
    name: "Auth Service",
    x: 400,
    y: 40,
    type: "auth",
    vulnerability: "JWT Weak Secret / IAM PrivEsc",
    blastRadius: "High",
    remediation: "Upgrade JWT signing key entropy and enforce IMDSv2 metadata protection",
    description: "Token authority. Issues identity claims and IAM role credentials."
  },
  {
    id: "postgres_db",
    name: "PostgreSQL DB",
    x: 560,
    y: 120,
    type: "target",
    vulnerability: "Crown Jewel Data Exfiltration",
    blastRadius: "Critical",
    remediation: "Microsegment database node network rules & encrypt at rest",
    description: "Crown Jewel host storing cardholder PAN details. Target of lateral SQL and BOLA queries."
  }
];

export default function AttackChainPage() {
  const [nodes, setNodes] = useState<NodeItem[]>(ARCH_NODES);
  const [selectedNode, setSelectedNode] = useState<NodeItem | null>(ARCH_NODES[0]);
  const [selectedDetail, setSelectedDetail] = useState<DetailInfo | null>(null);
  const [compromisedNodes, setCompromisedNodes] = useState<string[]>([]);
  const [telemetryEvents, setTelemetryEvents] = useState<TelemetryEvent[]>([]);

  // RAG & GNN State
  const [ragQuery, setRagQuery] = useState("");
  const [ragSearching, setRagSearching] = useState(false);
  const [ragResults, setRagResults] = useState<RAGResult[]>(MOCK_RAG_KNOWLEDGE["default"]);
  const [gnnInferring, setGnnInferring] = useState(false);
  const [gnnPathProb, setGnnPathProb] = useState<number>(87.4);

  const handleRagSearch = () => {
    setRagSearching(true);
    setTimeout(() => {
      setRagSearching(false);
    }, 450);
  };

  const handleRunGNN = () => {
    setGnnInferring(true);
    setTimeout(() => {
      setGnnInferring(false);
      setGnnPathProb(Math.round((85 + Math.random() * 12) * 10) / 10);
    }, 750);
  };

  // Load initial telemetry & listen on BroadcastChannel
  useEffect(() => {
    // 1. Initial load from localStorage
    try {
      if (typeof window !== "undefined") {
        const stored = JSON.parse(localStorage.getItem("axiom_compromised_nodes") || "[]");
        if (Array.isArray(stored) && stored.length > 0) {
          setCompromisedNodes(stored);
        }
        const lastEvent = localStorage.getItem("axiom_last_telemetry_event");
        if (lastEvent) {
          setTelemetryEvents([JSON.parse(lastEvent)]);
        }
      }
    } catch (e) {}

    // 2. BroadcastChannel live listener
    let channel: BroadcastChannel | null = null;
    try {
      if (typeof window !== "undefined" && "BroadcastChannel" in window) {
        channel = new BroadcastChannel("axiom_telemetry_channel");
        channel.onmessage = (event) => {
          const data: TelemetryEvent = event.data;
          if (data.type === "NODE_COMPROMISED" && data.compromisedNodes) {
            setCompromisedNodes(prev => Array.from(new Set([...prev, ...(data.compromisedNodes || [])])));
            setTelemetryEvents(prev => [data, ...prev].slice(0, 8));
          } else if (data.type === "TELEMETRY_RESET") {
            setCompromisedNodes([]);
            setTelemetryEvents(prev => [{ type: "RESET", timestamp: data.timestamp }, ...prev].slice(0, 8));
          }
        };
      }
    } catch (e) {}

    // 3. Storage event fallback
    const handleStorage = (e: StorageEvent) => {
      if (e.key === "axiom_compromised_nodes") {
        setCompromisedNodes(JSON.parse(e.newValue || "[]"));
      }
      if (e.key === "axiom_last_telemetry_event" && e.newValue) {
        setTelemetryEvents(prev => [JSON.parse(e.newValue || "{}"), ...prev].slice(0, 8));
      }
    };
    window.addEventListener("storage", handleStorage);

    return () => {
      if (channel) channel.close();
      window.removeEventListener("storage", handleStorage);
    };
  }, []);

  const triggerSimulatedExploit = (nodeIds: string[], name: string) => {
    const payload: TelemetryEvent = {
      type: "NODE_COMPROMISED",
      moduleName: name,
      compromisedNodes: nodeIds,
      timestamp: new Date().toLocaleTimeString()
    };
    setCompromisedNodes(prev => Array.from(new Set([...prev, ...nodeIds])));
    setTelemetryEvents(prev => [payload, ...prev].slice(0, 8));

    try {
      if (typeof window !== "undefined") {
        const updated = Array.from(new Set([...compromisedNodes, ...nodeIds]));
        localStorage.setItem("axiom_compromised_nodes", JSON.stringify(updated));
        localStorage.setItem("axiom_last_telemetry_event", JSON.stringify(payload));
        if ("BroadcastChannel" in window) {
          const channel = new BroadcastChannel("axiom_telemetry_channel");
          channel.postMessage(payload);
          channel.close();
        }
      }
    } catch (e) {}
  };

  const clearCompromisedNodes = () => {
    setCompromisedNodes([]);
    try {
      if (typeof window !== "undefined") {
        localStorage.removeItem("axiom_compromised_nodes");
        localStorage.removeItem("axiom_last_telemetry_event");
        if ("BroadcastChannel" in window) {
          const channel = new BroadcastChannel("axiom_telemetry_channel");
          channel.postMessage({ type: "TELEMETRY_RESET", timestamp: new Date().toLocaleTimeString() });
          channel.close();
        }
      }
    } catch (e) {}
  };

  // Helper checks for active compromised paths
  const isApiCompromised = compromisedNodes.includes("api_gateway");
  const isAuthCompromised = compromisedNodes.includes("auth_service");
  const isDbCompromised = compromisedNodes.includes("postgres_db");

  return (
    <div style={{ padding: 32, overflowY: "auto", flex: 1, background: "var(--bg)" }}>
      
      {/* Title & Sync Header */}
      <div style={{ marginBottom: 24, display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 16 }}>
        <div>
          <h1 style={{ fontSize: 24, fontWeight: 900, color: "#fff", display: "flex", alignItems: "center", gap: 8 }}>
            <GitBranch size={24} style={{ color: "var(--blue)" }} />
            AXIOM Attack Chain Visualizer
          </h1>
          <p style={{ color: "var(--muted)", fontSize: 13, marginTop: 4 }}>
            Map lateral traversal of verified vulnerabilities from entry nodes to database targets. Click nodes to view deep audit telemetry.
          </p>
        </div>

        {/* Live Telemetry Status Pill */}
        <div style={{ display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
          <div style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            background: compromisedNodes.length > 0 ? "rgba(239, 83, 80, 0.12)" : "rgba(0, 212, 255, 0.08)",
            border: compromisedNodes.length > 0 ? "1px solid rgba(239, 83, 80, 0.3)" : "1px solid rgba(0, 212, 255, 0.25)",
            borderRadius: 12,
            padding: "8px 14px",
            fontSize: 11.5,
            color: compromisedNodes.length > 0 ? "#ef5350" : "#00d4ff"
          }}>
            <span style={{
              width: 8,
              height: 8,
              borderRadius: "50%",
              background: compromisedNodes.length > 0 ? "#ef5350" : "#00d4ff",
              boxShadow: compromisedNodes.length > 0 ? "0 0 8px #ef5350" : "0 0 8px #00d4ff",
              animation: "pulse 1.5s infinite"
            }} />
            <strong>Telemetry Sync:</strong> {compromisedNodes.length > 0 ? `${compromisedNodes.length} Nodes Compromised` : "Baseline (Listening to Exploit Engine)"}
          </div>

          <button
            onClick={clearCompromisedNodes}
            style={{
              display: "flex",
              alignItems: "center",
              gap: 6,
              background: "var(--surface)",
              border: "1px solid var(--border)",
              borderRadius: 10,
              padding: "7px 12px",
              fontSize: 11,
              color: "var(--muted)",
              cursor: "pointer"
            }}
          >
            <RefreshCw size={12} />
            Reset State
          </button>
        </div>
      </div>

      {/* AI, Graph ML & Big Data Architecture Bar */}
      <div style={{
        marginBottom: 20,
        padding: "10px 16px",
        borderRadius: 12,
        background: "var(--surface)",
        border: "1px solid var(--border)",
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
        gap: 12,
        fontSize: 11
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ width: 8, height: 8, borderRadius: "50%", background: "#00d4ff" }} />
          <span style={{ color: "var(--muted)" }}>Graph Neural Network:</span>
          <strong style={{ color: "#fff" }}>PyTorch Geometric (GNN GraphSAGE)</strong>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ width: 8, height: 8, borderRadius: "50%", background: "var(--green)" }} />
          <span style={{ color: "var(--muted)" }}>Topology Database:</span>
          <strong style={{ color: "#fff" }}>Neo4j Cypher Graph Engine</strong>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ width: 8, height: 8, borderRadius: "50%", background: "#e8912d" }} />
          <span style={{ color: "var(--muted)" }}>Big Data Stream:</span>
          <strong style={{ color: "#fff" }}>Apache Spark + Kafka Real-Time Bus</strong>
        </div>
      </div>

      {/* Simulated Telemetry Triggers Banner */}
      <div style={{
        marginBottom: 20,
        padding: "12px 16px",
        borderRadius: 12,
        background: "var(--surface)",
        border: "1px solid var(--border)",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        flexWrap: "wrap",
        gap: 12
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12 }}>
          <Radio size={14} style={{ color: "var(--primary)" }} />
          <span style={{ color: "#fff", fontWeight: 700 }}>Telemetry Triggers:</span>
          <span style={{ color: "var(--muted)" }}>Launch verification from Exploit Engine or trigger local test:</span>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
          <button
            onClick={() => triggerSimulatedExploit(["api_gateway", "postgres_db"], "PHP SQL Injection Union (F-001)")}
            style={{
              background: "rgba(232, 145, 45, 0.12)",
              border: "1px solid rgba(232, 145, 45, 0.3)",
              color: "var(--primary)",
              borderRadius: 8,
              padding: "6px 12px",
              fontSize: 11,
              fontWeight: 700,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: 4
            }}
          >
            <Zap size={11} /> Simulate SQLi / BOLA Pivot
          </button>

          <button
            onClick={() => triggerSimulatedExploit(["auth_service", "postgres_db"], "AWS IAM / K8s PrivEsc (F-005)")}
            style={{
              background: "rgba(239, 83, 80, 0.12)",
              border: "1px solid rgba(239, 83, 80, 0.3)",
              color: "#ef5350",
              borderRadius: 8,
              padding: "6px 12px",
              fontSize: 11,
              fontWeight: 700,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: 4
            }}
          >
            <Zap size={11} /> Simulate Auth / Cloud Breach
          </button>

          <a
            href="https://14-exploitability-platform.vercel.app/exploit"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              color: "#00d4ff",
              fontSize: 11,
              fontWeight: 700,
              display: "flex",
              alignItems: "center",
              gap: 4,
              textDecoration: "none",
              marginLeft: 4
            }}
          >
            Open Exploit Engine <ExternalLink size={11} />
          </a>
        </div>
      </div>

      {/* Step 2 & 3: Unified Vector Memory & GNN Inference Controls */}
      <div style={{
        marginBottom: 20,
        padding: "16px 20px",
        borderRadius: 14,
        background: "var(--surface)",
        border: "1px solid var(--border)",
        display: "flex",
        flexDirection: "column",
        gap: 14
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 12 }}>
          <div>
            <span style={{ fontSize: 10, fontWeight: 800, textTransform: "uppercase", color: "#00d4ff" }}>
              Step 2 & 3: Unified Vector Memory (Qdrant) & Graph Neural Network (GNN)
            </span>
            <h3 style={{ fontSize: 15, fontWeight: 800, color: "#fff", display: "flex", alignItems: "center", gap: 8, marginTop: 2 }}>
              <Database size={16} color="#00d4ff" />
              Cross-Platform Vector Knowledge Mesh & Blast Radius Predictor
            </h3>
          </div>

          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              background: "rgba(0, 212, 255, 0.08)",
              border: "1px solid rgba(0, 212, 255, 0.25)",
              borderRadius: 10,
              padding: "6px 12px",
              fontSize: 11,
              color: "#00d4ff"
            }}>
              <Cpu size={13} />
              <span>GNN Lateral Reach Probability: <strong style={{ color: "#fff" }}>{gnnPathProb}%</strong></span>
            </div>

            <button
              onClick={handleRunGNN}
              disabled={gnnInferring}
              style={{
                background: "linear-gradient(135deg, #00d4ff, #0070f3)",
                border: "none",
                color: "#0a0f1a",
                padding: "7px 14px",
                borderRadius: 8,
                fontSize: 11,
                fontWeight: 800,
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                gap: 5
              }}
            >
              <Sparkles size={12} />
              {gnnInferring ? "Inferring GNN..." : "Run GNN Inference"}
            </button>
          </div>
        </div>

        {/* Vector Semantic Search Bar */}
        <div style={{ display: "flex", gap: 10 }}>
          <div style={{ position: "relative", flex: 1 }}>
            <Search size={14} style={{ position: "absolute", left: 12, top: "50%", transform: "translateY(-50%)", color: "var(--muted)" }} />
            <input
              type="text"
              value={ragQuery}
              onChange={e => setRagQuery(e.target.value)}
              placeholder="Query Vector Knowledge Mesh (e.g., 'Show all unauthenticated SQLi paths targeting PostgreSQL DB')..."
              style={{
                width: "100%",
                background: "var(--bg)",
                border: "1px solid var(--border)",
                borderRadius: 8,
                padding: "8px 12px 8px 34px",
                fontSize: 11.5,
                color: "#fff",
                outline: "none"
              }}
            />
          </div>
          <button
            onClick={handleRagSearch}
            disabled={ragSearching}
            style={{
              background: "var(--surface)",
              border: "1px solid var(--border)",
              color: "#fff",
              padding: "8px 14px",
              borderRadius: 8,
              fontSize: 11,
              fontWeight: 700,
              cursor: "pointer"
            }}
          >
            {ragSearching ? "Searching..." : "Vector Search"}
          </button>
        </div>

        {/* RAG Retrieved Findings Chips */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 10 }}>
          {ragResults.map((res, i) => (
            <div key={i} style={{ background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 8, padding: 10, fontSize: 10.5 }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 3 }}>
                <span style={{ fontWeight: 800, color: "#00d4ff" }}>[{res.platform}] {res.source}</span>
                <span style={{ color: "var(--green)", fontWeight: 700 }}>Cosine: {res.similarity}</span>
              </div>
              <div style={{ color: "#fff", fontWeight: 700, marginBottom: 2 }}>{res.finding}</div>
              <p style={{ color: "var(--muted)", margin: 0, lineHeight: 1.3 }}>{res.snippet}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Visualizer and Sidebar split */}
      <div style={{ display: "grid", gridTemplateColumns: "3fr 2fr", gap: 24 }}>
        
        {/* Left Side: SVG Canvas Graph */}
        <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 16, padding: 20, display: "flex", flexDirection: "column", minHeight: 380 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
            <h3 style={{ fontSize: 14, fontWeight: 800, color: "#fff", display: "flex", alignItems: "center", gap: 6 }}>
              <GitBranch size={16} style={{ color: "var(--blue)" }} />
              Architecture Propagation & Blast Radius Graph
            </h3>
            {compromisedNodes.length > 0 && (
              <span style={{ fontSize: 11, fontWeight: 800, color: "#ef5350", display: "flex", alignItems: "center", gap: 4 }}>
                <AlertTriangle size={12} /> Active Breach Path Highlighted (Red)
              </span>
            )}
          </div>
          
          <div style={{ flex: 1, background: "var(--bg)", borderRadius: 12, border: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "center", padding: 16, position: "relative" }}>
            <svg width="100%" height="260" viewBox="0 0 640 220" style={{ maxWidth: 640 }}>
              
              {/* Propagation Path Lines */}
              {/* Path 1: Client -> API Gateway */}
              <line
                x1="80" y1="130" x2="240" y2="130"
                stroke={isApiCompromised ? "#ef5350" : "var(--border)"}
                strokeWidth={isApiCompromised ? "3" : "2"}
                strokeDasharray={isApiCompromised ? "6 4" : "4 4"}
              />

              {/* Path 2: API Gateway -> Auth Service */}
              <line
                x1="240" y1="130" x2="400" y2="50"
                stroke={(isApiCompromised && isAuthCompromised) ? "#ef5350" : "var(--border)"}
                strokeWidth={(isApiCompromised && isAuthCompromised) ? "3" : "2"}
                strokeDasharray={(isApiCompromised && isAuthCompromised) ? "6 4" : "4 4"}
              />

              {/* Path 3: API Gateway -> Postgres DB */}
              <line
                x1="240" y1="130" x2="560" y2="130"
                stroke={(isApiCompromised && isDbCompromised) ? "#ef5350" : "var(--border)"}
                strokeWidth={(isApiCompromised && isDbCompromised) ? "3.5" : "2"}
                strokeDasharray={(isApiCompromised && isDbCompromised) ? "6 4" : "4 4"}
              />

              {/* Path 4: Auth Service -> Postgres DB */}
              <line
                x1="400" y1="50" x2="560" y2="130"
                stroke={(isAuthCompromised && isDbCompromised) ? "#ef5350" : "var(--border)"}
                strokeWidth={(isAuthCompromised && isDbCompromised) ? "3.5" : "2"}
                strokeDasharray={(isAuthCompromised && isDbCompromised) ? "6 4" : "4 4"}
              />

              {/* Render nodes */}
              {nodes.map(n => {
                const isSelected = selectedNode?.id === n.id;
                const isCompromised = compromisedNodes.includes(n.id);
                
                const nodeColor = isCompromised
                  ? "#ef5350"
                  : n.type === "entry" ? "var(--green)" :
                    n.type === "vulnerability" ? "#ff9500" :
                    n.type === "auth" ? "#ce93d8" : "#ef5350";

                return (
                  <g key={n.id} onClick={() => setSelectedNode(n)} style={{ cursor: "pointer" }}>
                    {/* Animated Ping Ring for Compromised Nodes */}
                    {isCompromised && (
                      <circle
                        cx={n.x}
                        cy={n.y}
                        r={28}
                        stroke="#ef5350"
                        strokeWidth="1.5"
                        fill="none"
                        opacity="0.5"
                      />
                    )}

                    <circle
                      cx={n.x}
                      cy={n.y}
                      r={isSelected ? 24 : 20}
                      fill={isCompromised ? "rgba(239, 83, 80, 0.2)" : "var(--surface)"}
                      stroke={nodeColor}
                      strokeWidth={isSelected ? 4 : isCompromised ? 3.5 : 2}
                      style={{ transition: "all 0.3s" }}
                    />
                    
                    <text
                      x={n.x}
                      y={n.y + 38}
                      textAnchor="middle"
                      fill={isCompromised ? "#ef5350" : isSelected ? "#fff" : "var(--muted)"}
                      fontSize={11}
                      fontWeight={isSelected || isCompromised ? 800 : 600}
                    >
                      {n.name}
                    </text>

                    <text
                      x={n.x}
                      y={n.y + 4}
                      textAnchor="middle"
                      fill={nodeColor}
                      fontSize={11.5}
                      fontWeight={950}
                    >
                      {isCompromised ? "🚨" : n.type === "entry" ? "E" : n.type === "vulnerability" ? "V" : n.type === "auth" ? "A" : "T"}
                    </text>
                  </g>
                );
              })}
            </svg>
          </div>

          {/* Live Ingestion Feed Ticker */}
          <div style={{ marginTop: 16, borderTop: "1px solid var(--border)", paddingTop: 12 }}>
            <span style={{ fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", color: "var(--muted)", display: "block", marginBottom: 6 }}>
              Live Telemetry Stream ({telemetryEvents.length} Events)
            </span>
            <div style={{ fontSize: 11, fontFamily: "monospace", color: "var(--muted)", display: "flex", flexDirection: "column", gap: 4 }}>
              {telemetryEvents.length === 0 ? (
                <span>[*] Telemetry listener active on BroadcastChannel(&apos;axiom_telemetry_channel&apos;). Awaiting exploit dispatch...</span>
              ) : (
                telemetryEvents.map((evt, idx) => (
                  <div key={idx} style={{ display: "flex", alignItems: "center", gap: 6, color: evt.type === "RESET" ? "var(--green)" : "#ef5350" }}>
                    <span>[{evt.timestamp}]</span>
                    <strong>{evt.type === "RESET" ? "RESET_EVENT" : "INTRUSION_ALERT"}:</strong>
                    <span>{evt.moduleName || "Exploit verified"} → Compromised [{evt.compromisedNodes?.join(", ")}]</span>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* Right Side: Audit Sidebar */}
        {selectedNode && (
          <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 16, padding: 20, display: "flex", flexDirection: "column", gap: 16 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <h3 style={{ fontSize: 16, fontWeight: 800, color: "#fff", display: "flex", alignItems: "center", gap: 6 }}>
                Node Audit: {selectedNode.name}
              </h3>
              <span
                onClick={() => setSelectedDetail(CHAIN_DETAILS[selectedNode.id])}
                style={{ cursor: "pointer", color: "var(--muted)", display: "flex", alignItems: "center" }}
                title="Click for full node impact details"
              >
                <InfoIcon size={14} />
              </span>
            </div>

            {compromisedNodes.includes(selectedNode.id) && (
              <div style={{
                background: "rgba(239, 83, 80, 0.15)",
                border: "1px solid rgba(239, 83, 80, 0.4)",
                borderRadius: 8,
                padding: "8px 12px",
                display: "flex",
                alignItems: "center",
                gap: 8,
                color: "#ef5350",
                fontSize: 11.5,
                fontWeight: 700
              }}>
                <AlertTriangle size={16} />
                <span>ACTIVE INTRUSION DETECTED (Compromised by Exploit Engine)</span>
              </div>
            )}

            <div style={{ fontSize: 12, display: "flex", flexDirection: "column", gap: 12, lineHeight: 1.5 }}>
              <div>
                <strong style={{ color: "var(--muted)", display: "block", marginBottom: 3 }}>Description:</strong>
                <p style={{ color: "var(--fg-2)" }}>{selectedNode.description}</p>
              </div>

              <div>
                <strong style={{ color: "var(--muted)", display: "block", marginBottom: 3 }}>Node Threat / Vulnerability:</strong>
                <span style={{ fontSize: 11.5, color: "#fff", background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 6, padding: "4px 8px", fontFamily: "monospace", display: "block", width: "fit-content" }}>
                  {selectedNode.vulnerability}
                </span>
              </div>

              <div style={{ display: "flex", justifyContent: "space-between", background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 8, padding: 12 }}>
                <span style={{ color: "var(--muted)" }}>Threat Blast Radius:</span>
                <strong style={{
                  color:
                    selectedNode.blastRadius === "Critical" || selectedNode.blastRadius === "High"
                      ? "#ef5350"
                      : "var(--green)"
                }}>{selectedNode.blastRadius}</strong>
              </div>

              <div>
                <strong style={{ color: "var(--muted)", display: "block", marginBottom: 4 }}>Mitigation Action:</strong>
                <p style={{ color: "var(--green)", fontWeight: 600 }}>{selectedNode.remediation}</p>
              </div>
            </div>
          </div>
        )}

      </div>

      {/* Interactive Detail Modal Dialog */}
      {selectedDetail && (
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: "rgba(0,0,0,0.8)",
            backdropFilter: "blur(4px)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000,
            padding: 16
          }}
        >
          <div
            className="animate-scaleIn"
            style={{
              background: "var(--surface)",
              border: "1px solid var(--border)",
              borderRadius: 16,
              width: "100%",
              maxWidth: 500,
              padding: 24,
              position: "relative"
            }}
          >
            <button
              onClick={() => setSelectedDetail(null)}
              style={{
                position: "absolute",
                top: 16,
                right: 16,
                background: "transparent",
                border: "none",
                color: "var(--muted)",
                cursor: "pointer"
              }}
            >
              <X size={18} />
            </button>

            {/* Header */}
            <div style={{ marginBottom: 20 }}>
              <span style={{
                fontSize: 9.5,
                fontWeight: 800,
                textTransform: "uppercase",
                padding: "2px 6px",
                borderRadius: 4,
                background: "rgba(0, 212, 255, 0.12)",
                color: "var(--blue)"
              }}>
                {selectedDetail.category}
              </span>
              <h3 style={{ fontSize: 18, fontWeight: 800, color: "#fff", marginTop: 8 }}>{selectedDetail.title}</h3>
            </div>

            {/* Content sections */}
            <div style={{ display: "flex", flexDirection: "column", gap: 16, fontSize: 12, lineHeight: "1.5" }}>
              <div>
                <strong style={{ color: "#fff", display: "block", marginBottom: 3 }}>What is it?</strong>
                <p style={{ color: "var(--fg-2)" }}>{selectedDetail.what}</p>
              </div>
              <div>
                <strong style={{ color: "#fff", display: "block", marginBottom: 3 }}>Why we check this?</strong>
                <p style={{ color: "var(--fg-2)" }}>{selectedDetail.why}</p>
              </div>
              <div>
                <strong style={{ color: "#fff", display: "block", marginBottom: 3 }}>How it impacts risk?</strong>
                <p style={{ color: "var(--fg-2)" }}>{selectedDetail.risk}</p>
              </div>
              {selectedDetail.impact && (
                <div style={{ display: "flex", justifyContent: "space-between", background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 8, padding: 12, marginTop: 4 }}>
                  <span style={{ color: "var(--muted)" }}>Propagation Impact:</span>
                  <strong style={{ color: "var(--blue)" }}>{selectedDetail.impact}</strong>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

    </div>
  );
}

