dbms.default_listen_address=127.0.0.1
dbms.memory.heap.initial_size=128m
dbms.memory.heap.max_size=256m
dbms.memory.pagecache.size=64m
dbms.directories.logs=/opt/vuln_intel/app/neo4j_logs
dbms.directories.run=/opt/vuln_intel/app/neo4j_run
