# ==============================================================================
# Rspamd DKIM Signing Module Configuration
# ==============================================================================

path = "/var/lib/rspamd/dkim/$domain.$selector.key";
selector = "default";
allow_username_mismatch = true;
sign_authenticated = true;
use_esld = true;
try_fallback = true;
use_redis = true;
key_prefix = "dkim_keys";
