"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import RiskSummaryBar from "@/components/dashboard/RiskSummaryBar";
import FindingsFilter from "@/components/dashboard/FindingsFilter";
import FindingsGrid from "@/components/dashboard/FindingsGrid";
import RiskTrendChart from "@/components/dashboard/RiskTrendChart";
import RiskGauge from "@/components/dashboard/RiskGauge";
import FINDINGS from "@/data/findings";
import { calculateRiskScore, severityCounts } from "@/lib/risk";
import type { Severity } from "@/types/sast";
import { CheckCircle2, ShieldAlert, Folder, X, Info } from "lucide-react";

const SEVERITY_ORDER: Record<string, number> = { Critical: 0, High: 1, Medium: 2, Low: 3 };

type DetailInfo = {
  title: string;
  category: string;
  what: string;
  why: string;
  risk: string;
  threshold?: string;
};

const DETAIL_DATA: Record<string, DetailInfo> = {
  // Top Row Summary Metrics
  "Risk Score": {
    title: "Project Risk Score",
    category: "Composite Security Index",
    what: "The overall threat index (0-100) calculated by combining vulnerability severities, exploit predictability models (EPSS), and code asset business exposure values.",
    why: "Allows CSOs and developers to immediately understand the absolute threat level of the code repository.",
    risk: "Vulnerability levels of 100 represent public API routes hosting critical injection flaws with confirmed reachability pathways.",
    threshold: "< 25.0% SLA Target"
  },
  "Critical": {
    title: "Critical Vulnerabilities",
    category: "Severe Vulnerability Count",
    what: "Flaws rated as Critical (CVSS >= 9.0) requiring immediate attention. Typically includes unauthenticated SQL Injections, Deserializations, or Command Injections.",
    why: "Attackers can immediately exploit these paths to compromise the runtime host or exfiltrate full data pools with zero prerequisites.",
    risk: "Complete server compromise, arbitrary remote execution gadgets, and total customer data breach.",
    threshold: "0 Tolerance Policy"
  },
  "High": {
    title: "High Vulnerabilities",
    category: "Severe Vulnerability Count",
    what: "Flaws rated as High (CVSS 7.0 - 8.9). These represent severe vulnerabilities that may require specific authentication credentials or minor environment variables.",
    why: "High severity vectors can easily escalate to system bypasses or logic errors if chained with low/medium vulnerabilities.",
    risk: "Privilege escalation, auth token bypass, sensitive configuration leaks, or database structure modifications.",
    threshold: "0 Tolerance Policy"
  },
  "Avg Confidence": {
    title: "Average Consensus Confidence",
    category: "Multi-Engine Concordance",
    what: "The consensus verification score generated by correlating matching syntax flows across CodeQL, Semgrep, Checkmarx, and Snyk.",
    why: "Drastically cuts down triage manual labor by confirming whether multiple engines identified the same logic flows.",
    risk: "Low average confidence indicators usually represent scanner syntax overlap noise; high average confidence indicates solid true positives.",
    threshold: "> 75.0% Recommended Target"
  },

  // Sentinel Gate items
  "New Vulnerabilities": {
    title: "New Vulnerabilities",
    category: "Sentinel Gate Metric",
    what: "Detects security weaknesses introduced in the latest codebase commit, merge request, or pull request.",
    why: "Preventing regressions is critical to keeping the overall technical debt low. Stopping fresh vulnerabilities at the gate forces immediate developer mitigation.",
    risk: "Critical risk of passing active vulnerabilities (such as SQL injection, SSRF, or command execution) into main branches and eventually production servers.",
    threshold: "0 Max Allowed"
  },
  "Coverage on New Code": {
    title: "Coverage on New Code",
    category: "Sentinel Gate Metric",
    what: "Measures the percentage of newly added or modified lines of code that are verified by automated tests.",
    why: "Ensures that developers are writing appropriate unit/integration tests for new business logic, protecting code health.",
    risk: "High risk of logic bypasses, hidden runtime crashes, or edge-case exploits occurring in unverified code paths.",
    threshold: "> 80.0% Required"
  },
  "Duplicated Lines": {
    title: "Duplicated Lines",
    category: "Sentinel Gate Metric",
    what: "Traces copy-pasted blocks of source code across different files or modules.",
    why: "Highly duplicated code complicates security updates. Fixing a vulnerability in one place but forgetting to update its duplicate leaves paths vulnerable.",
    risk: "Maintenance complexity and fragmented patches. Vulnerabilities get reintroduced as developers clone outdated, unsafe code fragments.",
    threshold: "< 3.0% Maximum"
  },
  "Security Hotspots Verified": {
    title: "Security Hotspots Verified",
    category: "Sentinel Gate Metric",
    what: "Code patterns that are security-sensitive and require manual expert validation (e.g. key lengths, CORS configurations, encryption modes).",
    why: "Traditional automated rule engines cannot evaluate business-logic authorization. Human review ensures cryptographic APIs are used properly.",
    risk: "Low-quality cryptography, overly permissive network configs, or insecure defaults bypassing automation checks.",
    threshold: "> 90.0% Required"
  },
  "Reliability Rating": {
    title: "Reliability Rating",
    category: "Sentinel Gate Metric",
    what: "A score derived from the count and severity of active reliability bugs in the codebase.",
    why: "Guarantees system uptime and protects the application against runtime errors.",
    risk: "Vulnerability to Denial of Service (DoS) due to unhandled exceptions, memory exhaustion, or memory leak exceptions.",
    threshold: "Grade A Required"
  },
  "Security Rating": {
    title: "Security Rating",
    category: "Sentinel Gate Metric",
    what: "A composite letter grade based on the severity of open vulnerabilities. A grade of 'E' indicates at least one critical vulnerability exists.",
    why: "Provides an instant compliance indicator of the application's overall risk posture.",
    risk: "Immediate threat of compromise. Grade E means there is an active vector that allows unauthenticated access or remote execution.",
    threshold: "Grade A Required"
  },

  // AppScan paths
  "src/main/java/com/api/": {
    title: "src/main/java/com/api/",
    category: "Threat Density Audit",
    what: "Audits Java controllers and REST routes that handle incoming HTTP queries and parameters.",
    why: "This is the primary exposure surface. It acts as the gateway connecting external user input to internal business logic.",
    risk: "Direct injection threats (SQLi, path traversal, OS Command Injection) if variables flow to execution sinks unsanitized.",
    threshold: "14.2 Bugs / KLOC (Critical Density)"
  },
  "src/main/resources/": {
    title: "src/main/resources/",
    category: "Threat Density Audit",
    what: "Static assets, database configurations, and environment property mappings.",
    why: "Monitors config parameters to prevent hardcoded passwords, insecure certificates, or database access leaks.",
    risk: "Exposure of API keys, plaintext database credentials, and critical deployment properties.",
    threshold: "0.0 Bugs / KLOC (Clean)"
  },
  "src/main/config/": {
    title: "src/main/config/",
    category: "Threat Density Audit",
    what: "Web configurations, CORS setups, authentication filters, and network middleware bindings.",
    why: "Validates security policy definitions, ensuring route controls and communication wrappers are actively enforced.",
    risk: "Overly permissive CORS rules, disabled CSRF tokens, or misconfigured security filters exposing backend routes.",
    threshold: "4.1 Bugs / KLOC (Medium Density)"
  },
  "src/main/auth/": {
    title: "src/main/auth/",
    category: "Threat Density Audit",
    what: "Authentication providers, JWT token verifiers, hashing algorithms, and session management logic.",
    why: "Governs identity boundaries. Protects authorization routines.",
    risk: "Credential compromises, JWT none algorithm signature bypasses, or weak encryption key usage.",
    threshold: "1.8 Bugs / KLOC (Low Density)"
  },

  // Checkmarx rules
  "OWASP A03:2021 (Injection)": {
    title: "OWASP A03:2021 (Injection)",
    category: "Compliance Alignment",
    what: "OWASP top standard addressing injection flaws (such as SQL Injection, LDAP Injection, and Command Injection).",
    why: "Injection is the most common and destructive web vulnerability, allowing attackers to access databases directly.",
    risk: "Complete database exfiltration, unauthorized admin commands execution, and data corruption.",
    threshold: "FAILED (2 Active Violations)"
  },
  "PCI-DSS Req 6.2.4 (Validation)": {
    title: "PCI-DSS Req 6.2.4 (Validation)",
    category: "Compliance Alignment",
    what: "Payment Card Industry rule requiring inputs to be fully validated and sanitized before DB entry.",
    why: "Protects cardholder metadata (PAN, CVVs) from theft.",
    risk: "PCI non-compliance fines, loss of card transaction capabilities, and database leak liability.",
    threshold: "FAILED (1 Active Violation)"
  },
  "NIST SI-10 (Input Validation)": {
    title: "NIST SI-10 (Input Validation)",
    category: "Compliance Alignment",
    what: "NIST SP 800-53 security control requiring federal information systems to check and sanitize input syntax.",
    why: "Ensures overall system boundaries are resilient to buffer overflow and command string injection.",
    risk: "Federal audit failures, system compromise, and command pipeline hijacking.",
    threshold: "FAILED (3 Active Violations)"
  },
  "ISO 27001 A.8.28 (Secure Coding)": {
    title: "ISO 27001 A.8.28 (Secure Coding)",
    category: "Compliance Alignment",
    what: "ISO code design requirement enforcing secure software development lifecycles (SSDLC).",
    why: "Establishes secure coding patterns across the entire engineering organization.",
    risk: "Loss of enterprise compliance certifications, leading to immediate business contract terminations.",
    threshold: "PASSED (0 Violations)"
  }
};

export default function DashboardContent() {
  const router       = useRouter();
  const searchParams = useSearchParams();

  const filter = (searchParams.get("severity") ?? "All") as Severity | "All";
  const search  = searchParams.get("q")    ?? "";
  const sortBy  = searchParams.get("sort") ?? "Severity";

  const [selectedDetail, setSelectedDetail] = useState<DetailInfo | null>(null);

  const update = useCallback(
    (key: string, value: string) => {
      const params = new URLSearchParams(searchParams.toString());
      if (!value || value === "All" || value === "Severity") {
        params.delete(key);
      } else {
        params.set(key, value);
      }
      router.replace(`/dashboard?${params.toString()}`, { scroll: false });
    },
    [router, searchParams]
  );

  const onFilter = (f: Severity | "All") => update("severity", f);
  const onSearch = (s: string)           => update("q", s);
  const onSort   = (s: string)           => update("sort", s);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "/" && !(e.target instanceof HTMLInputElement)) {
        e.preventDefault();
        const input = document.querySelector<HTMLInputElement>("input[placeholder*='Search']");
        input?.focus();
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, []);

  let results = [...FINDINGS];
  if (filter !== "All") results = results.filter(f => f.severity === filter);
  if (search.trim()) {
    const q = search.toLowerCase();
    results = results.filter(f =>
      f.title.toLowerCase().includes(q) ||
      f.cwe.toLowerCase().includes(q)   ||
      f.file.toLowerCase().includes(q)  ||
      f.owasp.toLowerCase().includes(q)
    );
  }
  if (sortBy === "Severity")        results.sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);
  else if (sortBy === "CVSS")       results.sort((a, b) => b.cvss - a.cvss);
  else if (sortBy === "Confidence") results.sort((a, b) => b.confidence - a.confidence);
  else if (sortBy === "File")       results.sort((a, b) => a.file.localeCompare(b.file));

  const counts    = severityCounts(FINDINGS);
  const riskScore = calculateRiskScore(FINDINGS);
  const hasFilter = filter !== "All" || search || sortBy !== "Severity";

  const openDetail = (key: string) => {
    const detail = DETAIL_DATA[key];
    if (detail) setSelectedDetail(detail);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

      {/* Header */}
      <div className="mb-8 flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white">Security Dashboard</h1>
          <p className="mt-1 text-sm" style={{ color: "var(--muted)" }}>
            Customer API · Last scan: <span className="text-white">2026-08-22</span> · {FINDINGS.length} findings
          </p>
        </div>
        <div className="flex items-center gap-3">
          <div
            className="px-4 py-2 rounded-xl text-sm"
            style={{ background: "rgba(52,199,89,0.08)", border: "1px solid rgba(52,199,89,0.25)", color: "var(--low)" }}
          >
            ✓ CodeQL · Semgrep · Joern · DataFlow
          </div>
          <div
            className="hidden sm:flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs"
            style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--muted)" }}
            title="Press / to focus search"
          >
            <kbd className="px-1.5 py-0.5 rounded text-[10px] font-mono"
              style={{ background: "var(--border)", color: "var(--foreground)" }}
            >
              /
            </kbd>
            to search
          </div>
        </div>
      </div>

      {/* Top row: Gauge + Metrics */}
      <div className="mb-6 grid grid-cols-1 lg:grid-cols-4 gap-4 items-stretch">
        <div
          className="flex flex-col items-center justify-center rounded-2xl p-6"
          style={{ background: "var(--surface)", border: "1px solid var(--border)" }}
        >
          <RiskGauge score={riskScore} size={160} />
          <p className="text-xs mt-3 text-center" style={{ color: "var(--muted)" }}>
            Composite risk · {FINDINGS.length} findings
          </p>
        </div>
        <div className="lg:col-span-3">
          <RiskSummaryBar findings={FINDINGS} onCardClick={openDetail} />
        </div>
      </div>

      {/* Risk trend */}
      <div className="mb-8">
        <RiskTrendChart currentScore={riskScore} />
      </div>

      {/* Next-Gen Integrations: AXIOM Sentinel Gate, AXIOM Volumetric Density Engine, AXIOM Regulatory Compliance Guard */}
      <div className="mb-8 grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* AXIOM Sentinel Gates Widget */}
        <div className="rounded-2xl p-5" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
          <div className="flex items-center justify-between mb-4">
            <span style={{ fontSize: 13, fontWeight: 700, color: "var(--fg)" }}>AXIOM Sentinel Gate</span>
            <span style={{
              fontSize: 10,
              fontWeight: 800,
              padding: "2px 8px",
              borderRadius: 4,
              background: "rgba(239,83,80,0.15)",
              color: "#ef5350"
            }}>FAILED</span>
          </div>
          
          <div className="space-y-2">
            {[
              { label: "New Vulnerabilities", value: "5", limit: "0 Max", ok: false },
              { label: "Coverage on New Code", value: "84.6%", limit: "> 80.0%", ok: true },
              { label: "Duplicated Lines", value: "0.2%", limit: "< 3.0%", ok: true },
              { label: "Security Hotspots Verified", value: "100%", limit: "> 90.0%", ok: true },
              { label: "Reliability Rating", value: "A", limit: "A Required", ok: true },
              { label: "Security Rating", value: "E", limit: "A Required", ok: false }
            ].map((gate, i) => (
              <div
                key={i}
                onClick={() => openDetail(gate.label)}
                className="hover-row"
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  borderBottom: "1px solid rgba(255,255,255,0.03)",
                  paddingBottom: 6,
                  cursor: "pointer",
                  padding: "4px 6px",
                  borderRadius: 6,
                  transition: "background 0.2s"
                }}
              >
                <div>
                  <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                    <div style={{ fontSize: 11, fontWeight: 600, color: "var(--fg)" }}>{gate.label}</div>
                    <Info size={10} className="text-slate-500" />
                  </div>
                  <div style={{ fontSize: 9.5, color: "var(--muted)" }}>Threshold: {gate.limit}</div>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <span style={{ fontSize: 11, fontWeight: 700, color: gate.ok ? "var(--green)" : "#ef5350" }}>{gate.value}</span>
                  {gate.ok ? (
                    <CheckCircle2 size={12} className="text-emerald-400" />
                  ) : (
                    <ShieldAlert size={12} className="text-red-500" />
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* AXIOM Volumetric Density Engine */}
        <div className="rounded-2xl p-5" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
          <div className="flex items-center justify-between mb-4">
            <span style={{ fontSize: 13, fontWeight: 700, color: "var(--fg)" }}>AXIOM Volumetric Density Engine</span>
            <span style={{ fontSize: 10, color: "var(--muted)" }}>Density: Bugs / KLOC</span>
          </div>

          <div className="space-y-3">
            {[
              { path: "src/main/java/com/api/", density: "14.2 / KLOC", bugs: "2 Critical", critical: true },
              { path: "src/main/resources/", density: "0.0 / KLOC", bugs: "Clean", critical: false },
              { path: "src/main/config/", density: "4.1 / KLOC", bugs: "1 Medium", critical: false },
              { path: "src/main/auth/", density: "1.8 / KLOC", bugs: "1 Low", critical: false }
            ].map((dir, i) => (
              <div
                key={i}
                onClick={() => openDetail(dir.path)}
                className="hover-row"
                style={{
                  display: "flex",
                  alignItems: "center",
                  background: "var(--bg)",
                  border: "1px solid var(--border)",
                  borderRadius: 8,
                  padding: "8px 12px",
                  cursor: "pointer",
                  transition: "background 0.2s"
                }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <Folder size={14} className={dir.critical ? "text-red-500" : "text-cyan-400"} />
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                      <span style={{ fontSize: 10.5, fontFamily: "monospace", color: "var(--fg)" }}>{dir.path}</span>
                      <Info size={9} className="text-slate-500" />
                    </div>
                    <div style={{ fontSize: 9.5, color: "var(--muted)", marginTop: 1 }}>{dir.bugs}</div>
                  </div>
                </div>
                <div style={{ marginLeft: "auto", textAlign: "right" }}>
                  <div style={{ fontSize: 10.5, fontWeight: 700, color: dir.critical ? "#ef5350" : "var(--fg)" }}>{dir.density}</div>
                  <div style={{ fontSize: 9, color: "var(--muted)" }}>Threat Density</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* AXIOM Regulatory Compliance Guard */}
        <div className="rounded-2xl p-5" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
          <div className="flex items-center justify-between mb-4">
            <span style={{ fontSize: 13, fontWeight: 700, color: "var(--fg)" }}>AXIOM Regulatory Compliance Guard</span>
            <span style={{ fontSize: 10, color: "var(--muted)" }}>Regulatory Auditor</span>
          </div>

          <div className="space-y-2">
            {[
              { rule: "OWASP A03:2021 (Injection)", ref: "CWE-89", compliant: false, issues: "2 Violations" },
              { rule: "PCI-DSS Req 6.2.4 (Validation)", ref: "PCI 6.2", compliant: false, issues: "1 Violation" },
              { rule: "NIST SI-10 (Input Validation)", ref: "NIST-SI", compliant: false, issues: "3 Violations" },
              { rule: "ISO 27001 A.8.28 (Secure Coding)", ref: "ISO-A8", compliant: true, issues: "Passed" }
            ].map((rule, i) => (
              <div
                key={i}
                onClick={() => openDetail(rule.rule)}
                className="hover-row"
                style={{
                  display: "flex",
                  alignItems: "center",
                  borderBottom: "1px solid rgba(255,255,255,0.03)",
                  paddingBottom: 6,
                  cursor: "pointer",
                  padding: "4px 6px",
                  borderRadius: 6,
                  transition: "background 0.2s"
                }}
              >
                <div style={{ flex: 1 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                    <div style={{ fontSize: 11, fontWeight: 600, color: "var(--fg)" }}>{rule.rule}</div>
                    <Info size={10} className="text-slate-500" />
                  </div>
                  <div style={{ fontSize: 9.5, color: "var(--muted)" }}>Reference: {rule.ref}</div>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: 6, marginLeft: "auto" }}>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontSize: 10, fontWeight: 700, color: rule.compliant ? "var(--green)" : "#ef5350" }}>
                      {rule.compliant ? "PASSED" : "FAILED"}
                    </div>
                    <div style={{ fontSize: 9, color: "var(--muted)" }}>{rule.issues}</div>
                  </div>
                  {rule.compliant ? (
                    <CheckCircle2 size={12} className="text-emerald-400" />
                  ) : (
                    <ShieldAlert size={12} className="text-red-500" />
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Filters */}
      <div className="mb-4">
        <FindingsFilter
          filter={filter}
          search={search}
          sortBy={sortBy}
          onFilter={onFilter}
          onSearch={onSearch}
          onSort={onSort}
          counts={counts}
        />
      </div>

      {/* Share hint */}
      {hasFilter && (
        <div
          className="mb-4 flex items-center gap-2 text-xs px-4 py-2 rounded-lg"
          style={{ background: "rgba(0,212,255,0.06)", border: "1px solid rgba(0,212,255,0.2)", color: "var(--primary)" }}
        >
          🔗 Filtered view — copy the URL to share this exact view with your team
        </div>
      )}

      {/* Count */}
      <div className="mb-4 text-sm" style={{ color: "var(--muted)" }}>
        Showing <span className="text-white font-medium">{results.length}</span> of {FINDINGS.length} findings
      </div>

      <FindingsGrid findings={results} />

      {/* Interactive Detail Modal Dialog */}
      {selectedDetail && (
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: "rgba(0,0,0,0.8)",
            backdropFilter: "blur(4px)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000,
            padding: 16
          }}
        >
          <div
            className="animate-scaleIn"
            style={{
              background: "var(--surface)",
              border: "1px solid var(--border)",
              borderRadius: 16,
              width: "100%",
              maxWidth: 500,
              padding: 24,
              position: "relative"
            }}
          >
            <button
              onClick={() => setSelectedDetail(null)}
              style={{
                position: "absolute",
                top: 16,
                right: 16,
                background: "transparent",
                border: "none",
                color: "var(--muted)",
                cursor: "pointer"
              }}
            >
              <X size={18} />
            </button>

            {/* Header */}
            <div style={{ marginBottom: 20 }}>
              <span style={{
                fontSize: 9.5,
                fontWeight: 800,
                textTransform: "uppercase",
                padding: "2px 6px",
                borderRadius: 4,
                background: "rgba(0,212,255,0.12)",
                color: "var(--primary)"
              }}>
                {selectedDetail.category}
              </span>
              <h3 style={{ fontSize: 18, fontWeight: 800, color: "#fff", marginTop: 8 }}>{selectedDetail.title}</h3>
            </div>

            {/* Content sections */}
            <div style={{ display: "flex", flexDirection: "column", gap: 16, fontSize: 12, lineHeight: "1.5" }}>
              <div>
                <strong style={{ color: "#fff", display: "block", marginBottom: 3 }}>What is it?</strong>
                <p style={{ color: "var(--fg-2)" }}>{selectedDetail.what}</p>
              </div>
              <div>
                <strong style={{ color: "#fff", display: "block", marginBottom: 3 }}>Why we check this?</strong>
                <p style={{ color: "var(--fg-2)" }}>{selectedDetail.why}</p>
              </div>
              <div>
                <strong style={{ color: "#fff", display: "block", marginBottom: 3 }}>How it impacts risk?</strong>
                <p style={{ color: "var(--fg-2)" }}>{selectedDetail.risk}</p>
              </div>
              {selectedDetail.threshold && (
                <div style={{ display: "flex", justifyContent: "space-between", background: "var(--bg)", border: "1px solid var(--border)", borderRadius: 8, padding: 12, marginTop: 4 }}>
                  <span style={{ color: "var(--muted)" }}>Configured Threshold Limit:</span>
                  <strong style={{ color: "var(--primary)" }}>{selectedDetail.threshold}</strong>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
